### PR TITLE
words: add "coyote" to the wordlist for tailnet names

### PR DESCRIPTION
**Pull request by 94tx**
I really like coyotes 🥺

### CODE REVIEW

**Comment by 94tx** [comment]
fuck I need to sign the commi

**Comment by catzkorn** [comment]
Could you update the commit title to be `words: add "coyote" to the wordlist for tailnet names`? It makes it in keeping with our convention for commit messages. 🐺

**Comment by creachadair** [comment]
> Could you update the commit title to be `words: add "coyote" to the wordlist for tailnet names`? It makes it in keeping with our convention for commit messages. 🐺 

We're very dogged about it 👀

**Review by catzkorn — APPROVED** [review]
Did you know that coyotes are faster than roadrunners? Cartoons lie to us!

Thanks for the contribution! 👍🏻

**Pull request merged**
