### PR TITLE
cmd/tailscale/cli: make update visible in list

### PR DESCRIPTION
**Pull request by noncombatant**
This also makes "HIDDEN: " work (requires the custom UsageFunc).

Updates #6995

### CODE REVIEW

**Review by awly — COMMENTED** [review]
How about we also move https://github.com/tailscale/tailscale/pull/8662/files#diff-5d05c094ca6c20d2455074acd16f67c05ac944caab86622408ff06502eb3aa70R138-R142 until after all the subcommands are populated?

**Comment by bradfitz** [comment]
FWIW it was hidden on purpose because it wasn't quite done. I'm fine unhiding it, as long as we're doing it intentionally and not just to like 'fix a bug' that it wasn't showing up or something?

**Comment by bradfitz** [comment]
Oh, there's even a comment above that section of the code saying that basically :)

**Review by bradfitz — APPROVED** [review]

**Comment by noncombatant** [comment]
Yes, @awly and I are working on a project to make `update` explicitly available everywhere.

**Comment by bradfitz** [comment]
> Yes, @awly and I are working on a project to make update explicitly available everywhere.

I guess the question is whether we unhide it before or after the project is complete. Because arguably I was also working on a project to make it available everywhere, but it was just very low priority and I didn't know when it'd be done so I kept it hidden... 😂

**Comment by bradfitz** [comment]
Maybe just hide it again before the next release if you're not happy about the state of things.

**Comment by noncombatant** [comment]
Let's keep it hidden until we're done. We'll just keep this PR un-landed until we're ready.

In the meantime, this PR makes the custom UsageFunc always set for all subcommands, as Andrew suggested: https://github.com/tailscale/tailscale/pull/8665

**Comment by noncombatant** [comment]
I think we can land this one now. What do you say?

**Review by awly — APPROVED** [review]

**Pull request merged**
