### PR TITLE
net/netns: add Windows support for bind-to-interface-by-route

### LINKED ISSUE #12551: FR: Windows support for binding to interface by route
Currently only implemented for macOS.

### PR DESCRIPTION
**Pull request by dblohm7**
This is implemented via GetBestInterfaceEx. Should we encounter errors or fail to resolve a valid, non-Tailscale interface, we fall back to returning the index for the default interface instead.

Fixes #12551

### CODE REVIEW

**Review by raggi — APPROVED** [review]
This implementation looks good as-is, but a couple of things we might consider:

- You can get the same result using the BSD sockets API by creating a UDP socket, then calling `connect(2)` (which won't send a packet). The connect will have a side effect of binding the local socket address to the best interface - so then you can use the local sockaddr API to get that interface index. This strategy is portable, and works on macOS, Windows, BSD's and Linux.
- I believe both this implementation and the one discussed above may have trouble when an exit node is selected, as they'll return the tailscale interface in that case. Is that covered somewhere by callers of this feature?

**Comment by dblohm7** [comment]
I'm not sure about your second point; I've pinged @andrew-d about what he knows about the history here.

**Comment by andrew-d** [comment]
> * I believe both this implementation and the one discussed above may have trouble when an exit node is selected, as they'll return the tailscale interface in that case. Is that covered somewhere by callers of this feature?

At least on macOS, the implementation [falls back to the default](https://github.com/tailscale/tailscale/blob/main/net/netns/netns_darwin.go#L111-L117) if the "bind to interface by route" logic picks the Tailscale interface, which is how we avoid a routing loop with exit nodes.

In this PR, it looks like we do the same thing [here](https://github.com/tailscale/tailscale/pull/12552/files#diff-3704c1c28e223278c3843ddee43e675f68e081d73e8a3229b30ed6c8016585a6R132-R138)?

**Comment by dblohm7** [comment]
Indeed, that's also in the Windows variant.

I'll file a follow-up issue for addressing this cross-platform.

**Pull request merged**
