### PR TITLE
wgengine/magicsock: reduce disco ping heartbeat aggressiveness a bit

### PR DESCRIPTION
**Pull request by bradfitz**
Bigger changes coming later, but this should improve things a bit in
the meantime.

Updates #3363

### CODE REVIEW

**Review by crawshaw — COMMENTED** [review]
When I see magic numbers change I wonder why. The commit message and comments doesn't explain why the change is being made, and it doesn't explain why it doesn't break any existing uses.

**Comment by bradfitz** [comment]
Updated comment message with background.

**Comment by crawshaw** [comment]
Leaving for @danderson. Looks like a dangling sentence in the commit message:

`* heartbeat from 2 seconds to 3 seconds: reducing rate from every`

**Comment by bradfitz** [comment]
Updated commit message.

**Review by danderson — APPROVED** [review]

**Pull request merged**
