### PR TITLE
clientupdate: restart tailscale after install on DSM6

### LINKED ISSUE #9361: 'tailscale update' not working on Synology NAS
### What is the issue?

1.48.1 introduced CPU architecture detection (https://github.com/tailscale/tailscale/issues/8927) 
1.48.2 has just been released, so I was eager to update with the newly introduced 'tailscale update' command via SSH on my Synology NAS. 

Below the output

xxxxxxx@Diskstation:/$ sudo tailscale update
Password: 
This will update Tailscale from 1.48.1 to 1.48.2. Continue? [y/n] y
Download size: 23846912
Downloaded 32768/23846912 (0.1%)
Downloaded 8028160/23846912 (33.7%)
Downloaded 19054592/23846912 (79.9%)
Downloaded 23846912/23846912 (100.0%)
hash matched
synopkg install failed: exit status 1
output:
Failed to install package /tmp/tailscale-update1377942038/tailscale-88f6282-1.48.2-6000048002-dsm6.spk, error = [290]

### Steps to reproduce

1) SSH log in into NAS
2) 'sudo tailscale update'
3) enter password

### Are there any recent changes that introduced the issue?

Not to my knowledge

### OS

Synology

### OS version

Synology DSM 6.2.4

### Tailscale version

1.48.1

### Other software

_No response_

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by awly**
DSM6 does not automatically restart packages on install, we have to do it explicitly.

Also, DSM6 has a filter for publishers in Package Center. Make the error message more helpful when update fails because of this filter not allowing our package.

Fixes #9361

### CODE REVIEW

**Review by noncombatant — APPROVED** [review]

**Comment by Smultie** [comment]
Not sure if this should've been fixed, but when running 'sudo tailscale update' from 1.48.2 to 1.50 I noticed it didn't restart the package. Maybe it's fixed within the code of 1.50, so it will start working when update from 1.50 to 1.5x?

**Comment by awly** [comment]
@Smultie yep, this fix was not included in 1.48.2 but should work on 1.50 and newer.
But please file an issue if the package is still not restarted when upgrading from 1.50.0.

**Comment by Smultie** [comment]
Thanks for the update. Makes sense. I'll make sure to let you know if the package doesn't auto-restart updating from 1.50 to 1.5x or 1.6

**Comment by Smultie** [comment]
Update from 1.50 to 1.50.1 went including auto-restart. Perfect!

**Pull request merged**
