### PR TITLE
go.toolchain.rev: update to Go 1.20.1

### PR DESCRIPTION
**Pull request by bradfitz**

### CODE REVIEW

**Review by danderson — APPROVED** [review]
early LGTM, but need to wait for the toolchain tarballs to finish publishing.

**Comment by bradfitz** [comment]
PTAL. I bumped x/net too for the http2/hpack fixes.

**Comment by bradfitz** [comment]
(Will re-run CI when the toolchain release is built)

**Review by danderson — APPROVED** [review]
Still LGTM, once the toolchain tarballs are live and CI is happy again.

**Pull request merged**
