### PR TITLE
cmd/k8s-operator: don't error for transient failures

### LINKED ISSUE #14072: k8s-operator: Don't log transient optimistic locking failures as error level
### What is the issue?

Several of the objects created by the operator's ProxyGroup controller are also updated by other controllers. This frequently causes error logs containing `"the object has been modified; please apply your changes to the latest version and try again"`. This is transient error that we expect to see from time to time in the control loop, and the next reconcile is highly likely to succeed applying the same changes, but it punts the ProxyGroup's status into an error state and prints a noisy error in the logs.

### Steps to reproduce

Deploy a `ProxyGroup` and tail the logs for the above error message. If not observed, scale the number of replicas up and down until observed.

```yaml
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: egress
spec:
  type: egress
  replicas: 2
  proxyClass: prod
```

### Are there any recent changes that introduced the issue?

_No response_

### OS

Linux

### OS version

_No response_

### Tailscale version

1.76.6

### Other software

_No response_

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by tomhjp**
Every so often, the ProxyGroup controller loses an optimistic locking race with other controllers that update the objects it creates. Stop treating this as an error event, and instead just log an info level log line for it.

Fixes #14072

### CODE REVIEW

**Review by irbekrm — APPROVED** [review]
Thanks @tomhjp!

We might want to do the same in some other reconcilers, but could be in another PR.

**Comment by tomhjp** [comment]
> We might want to do the same in some other reconcilers, but could be in another PR.

I added this for other controllers that were relatively straightforward, but I skipped a couple to avoid getting too bogged down, especially as I think we'll probably fix this properly with SSA in the future?

**Review by irbekrm — APPROVED** [review]
Thank you for picking this up!

**Comment by tomhjp** [comment]
Thanks!

**Pull request merged**
