### PR TITLE
net/interfaces: add IsExpensive and up state to State

### PR DESCRIPTION
**Pull request by bradfitz**
This change is [Reviewable](https://reviewable.io/reviews/tailscale/tailscale/278)

### CODE REVIEW

**Comment by bradfitz** [comment]
Also untested. Will test tomorrow when I'm back to my computer with Xcode.

/cc @bgentry

**Comment by bgentry** [comment]
Lmk if I can be of any help testing any of these changes :pray:

**Comment by bradfitz** [comment]
> Lmk if I can be of any help testing any of these changes 🙏

Once I test this before & after myself, I'll add you to our TestFlight builds.

But I don't actually know how to cut a build. I've barely learned how to press Play in Xcode.

**Comment by crawshaw** [comment]
Build->Archive in xcode to upload, then the rest is driven through their appstoreconnect website

**Comment by bradfitz** [comment]
Tested. This worked great.

**Pull request merged**
