### PR TITLE
cmd/tailscaled: add subcommands to install and remove tailscaled Wind…

### PR DESCRIPTION
**Pull request by alexbrainman**
…ows service

This change implements Windows version of install-system-daemon and
uninstall-system-daemon subcommands. When running the commands the
user will install or remove Tailscale Windows service.

Updates #1232

Signed-off-by: Alex Brainman <alex.brainman@gmail.com>

### CODE REVIEW

**Comment by alexbrainman** [comment]
Brad,

These commands output nothing when they succeed. And print error message when fail. I am not sure if it is correct approach, but I copied your code.

Also these commands need help text. I am not sure where I should put help text.

Also `install-system-daemon` and `uninstall-system-daemon` words don't sound like they belong on Windows. Should we have different command names for Windows? Maybe adjust existing commands so they fit on every OS.

Thank you.

Alex

**Comment by bradfitz** [comment]
> These commands output nothing when they succeed. And print error message when fail. I am not sure if it is correct approach, but I copied your code.

https://twitter.com/bradfitz/status/1329109889185062912

**Comment by bradfitz** [comment]
Let's wait on this change until after Tailscale 1.6 is out.

**Comment by alexbrainman** [comment]
> https://twitter.com/bradfitz/status/1329109889185062912

I agree with you for command output on Linux. But it felt wrong seeing this behaviour on Windows. Perhaps I have been using Windows for too long.

I don't think it is critical either way.

> Let's wait on this change until after Tailscale 1.6 is out.

SGTM. I will wait.

Alex

**Pull request merged**
