### PR TITLE
Add my name to the readme

### PR DESCRIPTION
**Pull request by Xe**

### CODE REVIEW

**Comment by bradfitz** [comment]
Actually, I'm not sure why that sentence was ever there from the beginning. Maybe we just remove it entirely? GitHub already renders this in several spots, including https://github.com/tailscale/tailscale/graphs/contributors linked off the main page.

**Comment by bradfitz** [comment]
(Otherwise this will continue to either be a maintenance burden or get out of sync)

Also, if somebody leaves the company I don't want to have to advertise it by removing them from that file.

**Comment by danderson** [comment]
I think we dropped that in there without thinking too much while rushing to open-source the thing, back in the dawn of time. Let's keep AUTHORS and ditch this wording?

**Comment by bradfitz** [comment]
AUTHORS is copyright holders (i.e. not us as named people). And we're not doing CONTRIBUTORS like Go because that's just in the git history.

**Comment by bradfitz** [comment]
Replaced by 7acd3397d5de11cd8dfb09f6a0bb7bf04f63a316

**Pull request closed without merging**
