### PR TITLE
net/netcheck: reenable TestNodeAddrResolve on Windows

### PR DESCRIPTION
**Pull request by raggi**
Updates #7876

### CODE REVIEW

**Comment by bradfitz** [comment]
Where was the fix?

**Comment by raggi** [comment]
> Where was the fix?

Sorry, this should have been a draft, it's passing locally, but wasn't in CI. This is to get an isolated failure case and diagnose it.

**Comment by andrew-d** [comment]
@raggi you authored this, so I can't assign you as a reviewer, but PTAL?

**Review by raggi — COMMENTED** [review]
LGTM, apparently I can't approve either!

**Review by maisem — COMMENTED** [review]
LGTM

**Pull request merged**
