### PR TITLE
version: calculate version info without using git tags.

### PR DESCRIPTION
**Pull request by danderson**
This makes it easier to integrate this version math into a submodule-ful
world. We'll continue to have regular git tags that parallel the information
in version/VERSION, so that builds out of this repository behave the same.

Signed-off-by: David Anderson <danderson@tailscale.com>

---
This change is [Reviewable](https://reviewable.io/reviews/tailscale/tailscale/868)

### CODE REVIEW

**Comment by danderson** [comment]
The overall version redo stuff can be simplified if we adopt this proposal. This is just the minimum necessary change to prove that it works and produces identical output to `git describe`.

Git tags work wonkily with submodules. Our current fix for that in git-fix-modules.sh involves hitting the network every time it's run, whereas before we could do a submodule checkout on the plane without internet. By keeping the "base release" information in a checked-in file, we can compute the same information without relying on git tags, and so their wonkiness in submodules is a non-issue, and we can continue to work on hypothetical planes that may still exist in the future.

Downside is we have to make sure to keep version/VERSION and git tags in sync to ensure that builds made directly from the tailscale repo continue to work and produce the same output. But that's fairly easy to accomplish.

Another downside is that there's an off-by-one error: VERSION is referencing the commit in which VERSION got updated, so we can't tag e.g. 1.2.0 and update VERSION, since updating VERSION we'd end up with 1.2.0+1 commit.

@apenwarr this is a minimal implementation of what you were thinking of. @bradfitz opinions on all this nonsense?

**Comment by josharian** [comment]
One advantage to keeping version in a file is that when 1.16 is out, we can use `//go:embed` to embed that version file in the binary, which will remove the need to script updates to version.go.

Another related option here is to make version.go the source of truth instead of having a separate version file.

**Comment by danderson** [comment]
We still need to script updates to compute the change count, which forms part of some of our versions. But I agree we can cut down on the amount of autogen, and cut it to zero-ish for stable releases.

Any thoughts on the off-by-one problem? To my mind that's the thing that kills this idea, unless there's a solution I missed.

**Comment by josharian** [comment]
> Any thoughts on the off-by-one problem? To my mind that's the thing that kills this idea, unless there's a solution I missed.

Always subtract one?

**Comment by josharian** [comment]
Or if you want to get fancy, when counting commits, filter out any commits that only touch VERSION. I'm sure git has a command line option for that. :)

**Comment by danderson** [comment]
If I tag 1.2.1, I would have to update VERSION in the following commit, because I don't know what commit hash to reference until the 1.2.1 commit has been made. So, if I check out the tag and try to compile it, VERSION will be wrong, because it's only one commit later that it got updated to "hey this is 1.2.1". I don't think I can solve that with arithmetic :/

**Comment by danderson** [comment]
Straw proposal: in the commit that gets tagged 1.2.1, update VERSION to be `1.2.1` (no commit hash). Then immediately make a followup commit that sets the hash. If no hash is present, assume the hash is HEAD.

Thoughts?

**Comment by josharian** [comment]
> If no hash is present, assume the hash is HEAD.

Why not assume the hash is the appropriate tag? Then you don't even necessarily have to immediately make a follow-up commit that sets the hash. (I think I'm missing something here; sorry for asking stupid questions.)

**Comment by danderson** [comment]
The goal of this file is to be able to compute the correct version numbers even in the presence of missing or lying tags (such as what happens to our submodules unless we hit the network to fix them). If we start relying on tags again, we can just use the code we already have :)

**Comment by apenwarr** [comment]
Probably bad idea: instead of putting the commitid into the file when
you update VERSION, just pull out the git history of the VERSION file
and pick the commit where it most recently changed :)

This also has the advantage of surviving rebases and
git-filter-branch, I guess, if that ever became necessary. And of
course, feels semantically nice for whoever needs to update the
VERSION file.

On Thu, Oct 29, 2020 at 4:07 PM Dave Anderson <notifications@github.com> wrote:
>
> The goal of this file is to be able to compute the correct version numbers even in the presence of missing or lying tags (such as what happens to our submodules unless we hit the network to fix them). If we start relying on tags again, we can just use the code we already have :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Avery Pennarun // CEO @ Tailscale

**Comment by danderson** [comment]
That could work. I expect there's a git oneliner for that :) I'll experiment with that option and see what it looks like for tomorrow's eng meet.

**Comment by apenwarr** [comment]
git rev-list --max-count=1 HEAD -- <filename>

On Thu, Oct 29, 2020 at 6:14 PM Dave Anderson <notifications@github.com> wrote:
>
> That could work. I expect there's a git oneliner for that :) I'll experiment with that option and see what it looks like for tomorrow's eng meet.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Avery Pennarun // CEO @ Tailscale

**Comment by danderson** [comment]
Updated per meeting outcome. The VERSION file can have two forms: `version-num hash` or just `version-num`. In the latter case, the git commit that last modified VERSION is used as the "base" hash for the purposes of computing change counts. I kept the version with an explicit hash so that we can correctly retroactively set 1.1 to the correct commit, but once we have new unstables and stables with VERSION, we can ditch that.

I'm going to follow this merge up immediately with another commit to clean up a bunch of our version computation stuff, since it's all overly complicated now that VERSION exists.

**Pull request merged**
