### PR TITLE
net/netns: add package for start of network namespace support

### PR DESCRIPTION
**Pull request by bradfitz**
net/netns: add package for start of network namespace support

And plumb in netcheck STUN packets.

TODO: derphttp, logs, control.

Updates #144

---
This change is [Reviewable](https://reviewable.io/reviews/tailscale/tailscale/422)

### CODE REVIEW

**Comment by danderson** [comment]
Can you call this dialer or something instead? Marking is the linux-specific solution, but we'll need something on Windows as well, where the thing looks completely different (but can still be accomplished with a dialer-like interface)

**Comment by bradfitz** [comment]
I started with nsdial but didn't like the dial part of name as it's also for listeners. Netcontrol seemed too vague. Ideas?

**Comment by danderson** [comment]
net/socket? Encompasses both listeners and dialers, and the word's a bit foreign in Go so there's not much overlap, even though we do end up futzing with sockets in the end.

**Comment by danderson** [comment]
Also fine with whatever name for now, it's easy to mass-rename later once the code's done.

**Comment by bradfitz** [comment]
netns?

**Comment by danderson** [comment]
not a huge fan of "ns" because the windows impl has nothing to do with namespaces afaik. But I guess it can be about the abstract concept of namespacing, not a specific technical implementation. netns SGTM.

**Pull request merged**
