### PR TITLE
feat: improve tailscale operator helm chart wildcard verbs

### PR DESCRIPTION
**Pull request by pierig-n3xtio**
I am currently working on my kubernetes security postures (cis-k8s, pss-baseline, pss-restricted, pci-dss etc...)  and thought I would try to address https://github.com/tailscale/tailscale/issues/13168

This change addresses:
K8sProhibitRoleWildcardAccess -> cis-k8s-v1.5.1-prohibit-role-wildcard-access

FYI full list of cis-k8s violations:
K8sPSPSeccomp -> cis-k8s-v1.5.1-psp-seccomp-default
K8sProhibitRoleWildcardAccess -> cis-k8s-v1.5.1-prohibit-role-wildcard-access
K8sPSPAllowPrivilegeEscalationContainer -> cis-k8s-v1.5.1-psp-allow-privilege-escalation
K8sPSPAllowedUsers -> cis-k8s-v1.5.1-psp-pods-must-run-as-nonroot
K8sPSPPrivilegedContainer -> cis-k8s-v1.5.1-psp-privileged-container

Comment:
K8sPSPSeccomp -> cis-k8s-v1.5.1-psp-seccomp-default
Might be addressable by adding a securityContext to a proxyclass, but I have not tried yet.
The other ones are most probably unfixable by nature!

### CODE REVIEW

**Comment by pierig-n3xtio** [comment]
the following tailscale-operator helm chart values help me with compliance.
Sharing here in case useful to someone.
```
values:
      annotations:
        network-controls/date: "2024-08-13"
      labels:
        pci-dss-firewall-audit: "pci-dss-2024q3"
      operatorConfig:
        hostname: "your-hostname"
        podAnnotations:
          network-controls/date: "2024-08-13"
        podLabels:
          pci-dss-firewall-audit: "pci-dss-2024q3"
        podSecurityContext:
          runAsNonRoot: false
          seccompProfile:
            type: RuntimeDefault
        securityContext:
          capabilities:
            drop:
              - NET_RAW
          runAsNonRoot: false
          seccompProfile:
            type: RuntimeDefault
          allowPrivilegeEscalation: false
      apiServerProxyConfig:
        mode: noauth
```
and the follwoing proxyclass:
```
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: proxy-labels
spec:
  statefulSet:
    annotations:
      network-controls/date: "2024-08-13"
    labels:
      pci-dss-firewall-audit: "pci-dss-2024q3"
    pod:
      labels:
        pci-dss-firewall-audit: "pci-dss-2024q3"
      annotations:
        network-controls/date: "2024-08-13"
```

**Comment by irbekrm** [comment]
Thank you for picking this up @pierig-n3xtio , this looks good to me 👍🏼 

Could you please reference this issue in your commit message? That will get the failing issuebot to pass. https://github.com/tailscale/tailscale?tab=readme-ov-file#contributing 

> K8sPSPSeccomp -> cis-k8s-v1.5.1-psp-seccomp-default

The operator proxies created for a Tailscale `Service` need NET_ADMIN. The proxies created for [Tailscale `Ingress`](https://tailscale.com/kb/1439/kubernetes-operator-cluster-ingress#exposing-a-service-using-ingress), so perhaps explicitly setting it via `ProxyClass` would work.

> K8sPSPAllowPrivilegeEscalationContainer -> cis-k8s-v1.5.1-psp-allow-privilege-escalation

I haven't experimented with this, but I _think_ we could explicitly disallow this

**Comment by pierig-n3xtio** [comment]
> Thank you for picking this up @pierig-n3xtio , this looks good to me 👍🏼
> 
> Could you please reference this issue in your commit message? That will get the failing issuebot to pass. https://github.com/tailscale/tailscale?tab=readme-ov-file#contributing
> 
> > K8sPSPSeccomp -> cis-k8s-v1.5.1-psp-seccomp-default
> 
> The operator proxies created for a Tailscale `Service` need NET_ADMIN. The proxies created for [Tailscale `Ingress`](https://tailscale.com/kb/1439/kubernetes-operator-cluster-ingress#exposing-a-service-using-ingress), so perhaps explicitly setting it via `ProxyClass` would work.
> 
> > K8sPSPAllowPrivilegeEscalationContainer -> cis-k8s-v1.5.1-psp-allow-privilege-escalation
> 
> I haven't experimented with this, but I _think_ we could explicitly disallow this

commit message updated!

**Comment by irbekrm** [comment]
@pierig-n3xtio thanks for updating the commit message!

I forgot to mention that you also need to update the static manifests that are generated from the chart templates.
You can do that by running `make kube-generate-all` and adding the result to your commit

**Comment by pierig-n3xtio** [comment]
@irbekrm thanks for the details~ I updated the operator.yaml file as well.

**Review by irbekrm — APPROVED** [review]
Thank you for the contribution!

**Pull request merged**
