### PR TITLE
cmd/tailscaled, wgengine/router: graceful shutdown, unify dns

### PR DESCRIPTION
**Pull request by dshynkev**
This combines several thematically related changes:
- When interrupted or killed with `SIGTERM`, `tailscaled` intercepts the signal and shuts down gracefully by cancelling the context of `ipnserver.Run`. Related changes that make shutdown actually work are included.
- a `tailscale down` command is added, which sends `Quit` to `BackendServer`, causing `ipnserver.Run` in `tailscaled` to return, behaving similarly to the graceful shutdown.
- `{replace,restore}ResolvConf`, which turn out to work across Linux, FreeBSD, OpenBSD macOS (tested on Void Linux, CentOS 8, Ubuntu 20.04, FreeBSD 12.1), are factored out in a separate file.
- The `router` package gains a `Cleanup` function. Correspondingly, a `--cleanup` flag is added to `tailscaled`. `tailscaled --cleanup` invokes `router.Cleanup()` and exits.

In total, setting DNS via the admin console should have effect on all the listed systems, with the old configuration restored when `tailscaled` is terminated. The next set of changes I'll push includes wiring Magic DNS into this and exposing `corp-dns` as a togglable option.

---
This change is [Reviewable](https://reviewable.io/reviews/tailscale/tailscale/514)

### CODE REVIEW

**Comment by dshynkev** [comment]
This represents a state that is known to work. I will now add a different implementation of graceful shutdown now, for contrast: the fork with two pipes, where child shuts down if parent dies and parent calls `.Cleanup` if child dies.

**Comment by danderson** [comment]
Will review in detail later, but - `tailscale down` should not be killing the daemon. Nothing in the CLI should be doing that. `tailscale down` as a counterpart to `up` just means "shut down the mesh network and stop routing".

**Comment by dshynkev** [comment]
Should there _be_ a way to kill the daemon, other than signalling it?

**Comment by dshynkev** [comment]
OK, I'll keep it out of this PR, in that case, since `up -> down -> up` doesn't seem to work naively. This also makes the extent of the changes narrowef.

**Comment by taisph** [comment]
The OpenVPN client can manage DNS settings without ever touching the resolv.conf file which is definitely preferable in our working environment. Any reason tailscale shouldn't use the same approach?

**Comment by dshynkev** [comment]
> The OpenVPN client can manage DNS settings (on Ubuntu) without ever touching the resolv.conf file which is definitely preferable in our working environment. Any reason tailscale shouldn't use the same approach?

Yes, that can be done per this [TODO](https://github.com/tailscale/tailscale/pull/514/files#diff-7068b92941f2b2d82e8a195c90031e55R827). I initially thought I'd hold off on piling too many things into one PR, since the `resolv.conf` route definitely works. Now that I know it isn't ideal for you, though, I'll tackle it. Thanks for bringing this up!

**Comment by dshynkev** [comment]
A downside of playing along with `systemd-resolved` (which OpenVPN seems to also suffer from, as far as I can tell) is that it doesn't allow us to become a global DNS proxy: at best, we can enable `DNS default route` on our interface by adding `~.` as a routing-only domain, but even then we will compete with other interfaces which also enable it, so queries will leak.

Perhaps it is reasonable to have two modes: **global**, where we must circumvent `systemd-resolved` and replace `/etc/resolv.conf` to ensure that we are the system-wide DNS proxy, and **scoped**, where we play along with `systemd-resolved` if it is available, only receiving queries for subdomains of `ipn.dev` (or whatever we choose as the root of names for Magic DNS) and of the search domains listed in the admin panel.

To help make an informed decision, why do you prefer to avoid replacing `resolv.conf`, @taisph? Right now, the intent of this is to allow you to use a separate set of nameservers (set in the admin panel) _globally_ when Tailscale is up, which is an invasive action by design. When this is used for Magic DNS, we will proxy non-matching queries to the nameservers from the old `resolv.conf`. There will be hitches there when _not_ using `systemd-resolved`, e.g. when the network state changes and we get new nameservers over DHCP.  When using `systemd-resolved`, though, this ought to be completely transparent, since the "old" nameserver will always be just `localhost` (the `systemd-resolved` stub resolver).

**Comment by taisph** [comment]
> A downside of playing along with `systemd-resolved` (which OpenVPN seems to also suffer from, as far as I can tell) is that it doesn't allow us to become a global DNS proxy: at best, we can enable `DNS default route` on our interface by adding `~.` as a routing-only domain, but even then we will compete with other interfaces which also enable it, so queries will leak.

While I'm sure there are use cases for overriding the global DNS, it usually comes with the side effect of being partially isolated from local network equipment in my experience. As such, we've avoided doing it. Making it an option for those who need it would be a good solution though.


> To help make an informed decision, why do you prefer to avoid replacing `resolv.conf`, @taisph? Right now, the intent of this is to allow you to use a separate set of nameservers (set in the admin panel) _globally_ when Tailscale is up, which is an invasive action by design. When this is used for Magic DNS, we will proxy non-matching queries to the nameservers from the old `resolv.conf`. There will be hitches there when _not_ using `systemd-resolved`, e.g. when the network state changes and we get new nameservers over DHCP. When using `systemd-resolved`, though, this ought to be completely transparent, since the "old" nameserver will always be just `localhost` (the `systemd-resolved` stub resolver).

Replacing resolv.conf seems to make NetworkManager overwrite it on Ubuntu when switching between connections (wifi, cabled, mobile). Systemd also doesn't seem to recover from removing the symlink so if tailscale fails to restore the symlink, the user might be left without a working DNS - at least until NetworkManager decides to overwrite it.

I assume Magic DNS will live in a specific domain which could be set as as search domain without the necessity of needing it to be global?

**Comment by danderson** [comment]
We have to support systems that aren't doing stuff like resolvconf, networkmanager, or resolved. The current logic that replaces /etc/resolv.conf is for those systems.

Separately (although it looks like Dmytro implemented it now), we're going to detect and use DNS config management facilities if they exist on the system, so the common case on desktop systems will be to not replace /etc/resolv.conf.

**Comment by dshynkev** [comment]
Regarding the local/global separation (where "local" is "bound to interface and only affecting subdomains of this configurable list of domains"), here is the picture so far:
### Global only
- `resolvconf` essentially only supports global configuration: when merging two configs (i.e. when in non-exclusive mode), it just outputs a combined list of nameservers, which is pretty much useless to us: even if we get all the queries, we're racing against other nameservers and this can't be reliable. We will want to use exclusive mode only, which works really well: good citizens like NetworkManager [do not](https://github.com/NetworkManager/NetworkManager/blob/cb9a6f3b9207169a9ce742562874a6d75fb93d60/src/dns/nm-dns-manager.c#L754) use it, so our config will survive network changes.
    - Has by far the simplest API and will fight over `/etc/resolv.conf`, so it makes good sense to support it.
    - Seems to require cleanup, though one wouldn't think so from the docs.
- Replacing `/etc/resolv.conf` is fundamentally global.
    - We have to support this for e.g. OpenBSD in any case.
    - Requires cleanup.
### Local only
- `systemd-resolved` seems to only allow this with their [DBus API](https://www.freedesktop.org/wiki/Software/systemd/resolved/), unless we want to mess with other interfaces' settings. An interface with the default route (not us) automatically has `DNS default route` enabled, which prevents us from being a global DNS proxy.
    - Will gracefully step aside if we unlink `/etc/resolv.conf` from the one it owns, so we can use the "replace `/etc/resolv.conf`" method if we really want to apply our settings globally.
    - As a result, we _don't_ really need to support it, given that it is the odd one out. I've already implemented this, though, and it works really well for the local case: unlike the previous two methods, it doesn't require cleanup.
### Local or global
- We can talk to `NetworkManager` directly over its [DBus API](https://developer.gnome.org/NetworkManager/1.2/gdbus-org.freedesktop.NetworkManager.html#gdbus-property-org-freedesktop-NetworkManager.GlobalDnsConfiguration). There we can set `GlobalDnsConfiguration` (and hope that no one else has this bright idea) or muck with interface-bound settings, just like with `system-resolved`.
    - If `resolvconf` is available, `NetworkManager` should use it. Otherwise, `NetworkManager` will handle `/etc/resolv.conf` directly, putting us in conflict. We probably have to support talking to it for that reason, since this seems to be the default configuration of at least CentOS 8.

Given all the above, perhaps it makes sense to expose a `--global-dns` flag to decide whether we will settle for the no-fighting, no-cleanup local route when possible or try to become the global proxy at the risk of conflict. It seems that we are just barely able to always guarantee the global option. Do you have any thoughts, @danderson?

**Comment by dshynkev** [comment]
This is broken up and superseded by #536.

**Pull request closed without merging**
