### PR TITLE
Fix docstring on wireguardGoString to match args

### PR DESCRIPTION
**Pull request by evankanderson**
@danderson linked this on Twitter and I noticed the mismatch.

### CODE REVIEW

**Comment by bradfitz** [comment]
Sorry, we do that whole DCO Signed-Off-By thing in lieu of CLAs.

**Comment by bradfitz** [comment]
Also, while you're fixing your commit message, could you make the title start with `wgengine/wglog: fix ...` ?

**Comment by evankanderson** [comment]
I'll get to the DCO later tonight when I'm not on my phone...

**Comment by evankanderson** [comment]
Done, thanks for humoring me.

**Comment by danderson** [comment]
The CI failure is unrelated, and I fixed it separately. I'll just rebase and merge, rather than force you to rebase just to get a clean CI.

Thanks!

**Pull request merged**
