### PR TITLE
Upgrade gvisor

### PR DESCRIPTION
**Pull request by andig**
Fix https://github.com/tailscale/tailscale/issues/6554

### CODE REVIEW

**Comment by bradfitz** [comment]
We'll wait until 1.34.0 is out (soon) for this.

**Comment by andig** [comment]
No problem. I just wanted to see if I could tackle this after the classification didn‘t make it likely to be a mainstream issue ;)

**Comment by bradfitz** [comment]
Fix the DCO error meanwhile? Amend your commit with -s and force push?

**Comment by andig** [comment]
I'm seeing one error on MacOS, but not on main:

```
--- FAIL: TestNetstackLeakMode (0.00s)
    netstack_test.go:92: refs.leakMode is 0, want a non-zero value
FAIL
FAIL	tailscale.com/wgengine/netstack	0.478s
```

**Comment by andig** [comment]
@bradfitz not sure how to proceed?

**Comment by DentonGentry** [comment]
1.34.0 was released on Monday, so we are at a good time to do something like this.
I had the PR run the continuous integration tests yesterday, they all fail with variations of:

```
Error: net/tstun/tap_linux.go:330:16: undefined: header.Checksum
Error: Process completed with exit code 2.
```

**Comment by andig** [comment]
Mhhm. I do not see this on my local machine on MacOS. I'd need help here for Linux. Looks like another change in gvisor.

**Comment by andig** [comment]
@bradfitz @DentonGentry I'm stuck and need support here. Running on MacOS I cannot analyse/debug this issue. Without resolving, debugging apps using Tailscale is currently not possible on M1 Macs due to https://github.com/google/gvisor/issues/8149.

**Comment by andig** [comment]
@bradfitz any chance to get help with this? Without resolving we can't integrate Tailscale as it kills debugging in the dev environment on MacOS M1.

**Comment by jwhited** [comment]
@andig usage of `gvisor.dev/gvisor/pkg/tcpip/header.Checksum()` can be replaced with `gvisor.dev/gvisor/pkg/tcpip/checksum.Checksum()`.

**Comment by bradfitz** [comment]
Copied this to #6820 with @jwhited and other fixes. Should be happy there now.

**Comment by andig** [comment]
Confirmed debugging is possible on M1 now. Much appreciated!

**Pull request closed without merging**
