### PR TITLE
go.mod: bump github.com/mdlayher/netlink, github.com/jsimonetti/rtnetlink

### PR DESCRIPTION
**Pull request by mdlayher**
Signed-off-by: Matt Layher <mdlayher@gmail.com>

The netlink and rtnetlink libraries have had some recent changes to improve corner case handling and performance. I also ran `go mod tidy` after pulling the new versions.

### CODE REVIEW

**Comment by bradfitz** [comment]
Sorry, merge conflicts after #1374 just went in. Rebase?

**Comment by bradfitz** [comment]
Also, I'm not a huge fan of this:

```patch
diff --git a/cmd/tailscaled/depaware.txt b/cmd/tailscaled/depaware.txt
index 64e9d34..629eb89 100644
--- a/cmd/tailscaled/depaware.txt
+++ b/cmd/tailscaled/depaware.txt
@@ -8,6 +8,12 @@ tailscale.com/cmd/tailscaled dependencies: (generated by github.com/tailscale/de
    W 💣 github.com/go-ole/go-ole/oleutil                             from tailscale.com/wgengine/winnet
    L 💣 github.com/godbus/dbus/v5                                    from tailscale.com/wgengine/router/dns
         github.com/google/btree                                      from gvisor.dev/gvisor/pkg/tcpip/header+
+   L 💣 github.com/google/go-cmp/cmp                                 from github.com/mdlayher/netlink
+   L    github.com/google/go-cmp/cmp/internal/diff                   from github.com/google/go-cmp/cmp
+   L    github.com/google/go-cmp/cmp/internal/flags                  from github.com/google/go-cmp/cmp+
+   L    github.com/google/go-cmp/cmp/internal/function               from github.com/google/go-cmp/cmp
+   L 💣 github.com/google/go-cmp/cmp/internal/value                  from github.com/google/go-cmp/cmp
+   L    github.com/josharian/native                                  from github.com/mdlayher/netlink+
    L 💣 github.com/jsimonetti/rtnetlink                              from tailscale.com/wgengine/monitor
    L    github.com/jsimonetti/rtnetlink/internal/unix                from github.com/jsimonetti/rtnetlink
         github.com/klauspost/compress/fse                            from github.com/klauspost/compress/huff0
```

`go-cmp` is pretty large, and it doesn't look like you actually need it: it's only used by your `fuzz.go`, which perhaps is just missing build tags?

Yeah, confirmed: if I add `+build gofuzz` to your `fuzz.go`, those deps disappear in depaware.

Us pulling in `github.com/josharian/native` is also slightly redundant (for us) in that we already have https://pkg.go.dev/tailscale.com/util/endian/ but I guess that's our problem.

Maybe we should unify both versions into, say, `go4.org/endian`? @josharian?

**Comment by josharian** [comment]
Unification SGTM. I'll make mine a forwarding package once that is done. Balls in your court for that.

**Comment by mdlayher** [comment]
Good call on the build tags, done. Rebased and updated to netlink@v1.3.2. @bradfitz PTAL.

**Pull request merged**
