### PR TITLE
net/dns/publicdns: Add Mullvad DoH

### PR DESCRIPTION
**Pull request by nshalman**
See https://mullvad.net/en/help/dns-over-https-and-dns-over-tls/

### CODE REVIEW

**Comment by bradfitz** [comment]
Did this change work for you?

This fails the opt-in actually-hit-the-network tests:

```
$ go test -v -run=TestDoH tailscale.com/net/dns/resolver --test-doh
...
=== RUN   TestDoH/https://doh.mullvad.net/dns-query
    doh_test.go:60: Post "https://doh.mullvad.net/dns-query": EOF
=== RUN   TestDoH/https://adblock.doh.mullvad.net/dns-query
    doh_test.go:60: Post "https://adblock.doh.mullvad.net/dns-query": net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x00\x00\x06\x04\x00\x00\x00\x00\x00\x00\x03\x00\x00\x01\x90"
=== RUN   TestDoH/https://cloudflare-dns.com/dns-query
...
--- FAIL: TestDoH (1.62s)
    --- PASS: TestDoH/https://cloudflare-dns.com/dns-query (0.30s)
    --- PASS: TestDoH/https://security.cloudflare-dns.com/dns-query (0.25s)
    --- PASS: TestDoH/https://family.cloudflare-dns.com/dns-query (0.23s)
    --- PASS: TestDoH/https://dns.google/dns-query (0.14s)
    --- PASS: TestDoH/https://dns.quad9.net/dns-query (0.21s)
    --- PASS: TestDoH/https://dns10.quad9.net/dns-query (0.20s)
    --- FAIL: TestDoH/https://doh.mullvad.net/dns-query (0.15s)
    --- FAIL: TestDoH/https://adblock.doh.mullvad.net/dns-query (0.15s)
```

**Comment by mnordhoff** [comment]
"`dig +https example.com @doh.mullvad.net`" and "`dig +https example.com @adblock.doh.mullvad.net`" work for me, for what it's worth.

**Comment by nshalman** [comment]
> Did this change work for you?

I haven't had a chance to test it, no (it was sitting in a local experiments branch, looked trivially correct (ha!) and I wanted to get it out somewhere it could be seen by anyone else who might find it useful.)

Thank you for the tip on the existing tests. I'm going to mark this PR as WIP for now (but for other readers, I have no objection to some one else picking this up before I get a chance to finish it....)

**Comment by bradfitz** [comment]
Looks like maybe it's HTTP/2-only?

**Comment by nshalman** [comment]
> Looks like maybe it's HTTP/2-only?

Seems like it. This change "fixes" the tests:
```diff
diff --git a/net/dns/resolver/forwarder.go b/net/dns/resolver/forwarder.go
index f51325e8..7fda4aca 100644
--- a/net/dns/resolver/forwarder.go
+++ b/net/dns/resolver/forwarder.go
@@ -406,6 +406,7 @@ func (f *forwarder) getKnownDoHClientForProvider(urlBase string) (c *http.Client
        })
        c = &http.Client{
                Transport: &http.Transport{
+                       ForceAttemptHTTP2: true,
                        IdleConnTimeout: dohTransportTimeout,
                        DialContext: func(ctx context.Context, netw, addr string) (net.Conn, error) {
                                if !strings.HasPrefix(netw, "tcp") {
```

**Comment by nshalman** [comment]
https://pkg.go.dev/net/http#Transport says that
```
	// ForceAttemptHTTP2 controls whether HTTP/2 is enabled when a non-zero
	// Dial, DialTLS, or DialContext func or TLSClientConfig is provided.
	// By default, use of any those fields conservatively disables HTTP/2.
	// To use a custom dialer or TLS config and still attempt HTTP/2
	// upgrades, set this to true.
```

So I assume that HTTP/2 isn't being used in the code as it is currently due to the use of the explicit `DialContext` visible in the diff above.

I'm not totally certain how to proceed. Thanks for your attention and help!!

**Comment by nshalman** [comment]
> I'm not totally certain how to proceed.

After reading that comment again, I think the only option that continues to use the non-nil `DialContext` is indeed using `ForceAttemptHTTP2`.

I will update the PR accordingly, and leave it to your discretion whether you folks think it's okay to enable it.

**Review by bradfitz — APPROVED** [review]

**Comment by bradfitz** [comment]
Yup, `ForceAttemptHTTP2` seems right.

**Pull request merged**
