### PR TITLE
go.mod, etc: bump gvisor

### LINKED ISSUE #6554: FR: update to gvisor `v0.0.0-20221129015920-2aaad2204dda` or later
### What is the issue?

I had to upgrade gvisor due to https://github.com/google/gvisor/issues/8149:

```
go get -u gvisor.dev/gvisor@go
go: upgraded gvisor.dev/gvisor v0.0.0-20220817001344-846276b3dbc5 => v0.0.0-20221129015920-2aaad2204dda
```

Now build fails:

```
# tailscale.com/net/tstun
../../go/pkg/mod/tailscale.com@v1.32.3/net/tstun/wrap.go:186:16: undefined: stack.PacketBuffer
../../go/pkg/mod/tailscale.com@v1.32.3/net/tstun/wrap.go:534:19: invalid operation: res.packet != nil (operator != not defined on untyped nil)
../../go/pkg/mod/tailscale.com@v1.32.3/net/tstun/wrap.go:728:56: undefined: stack.PacketBuffer
../../go/pkg/mod/tailscale.com@v1.32.3/net/tstun/wrap.go:827:60: undefined: stack.PacketBuffer

```

It would be great to be able to compile and debug tailscale again.

### Steps to reproduce

See above

### Are there any recent changes that introduced the issue?

gvisor upgrade

### OS

macOS

### OS version

13.0

### Tailscale version

1.32.3

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by bradfitz**
Fixes #6554

### CODE REVIEW

**Comment by bradfitz** [comment]
Originally from @andig in #6612; I rebased, squashed, reformatted the commit message and fixed one bit that didn't compile.

**Comment by bradfitz** [comment]
Ah, leak mode changed.

https://github.com/google/gvisor/commit/175db901ca2b491c413ce3e9880f30259a8d306d

DisabledMode is now the zero value and the Unitialized zero value was deleted.

cc @raggi

**Comment by bradfitz** [comment]
Okay, deleted that test (no longer applicable) and simplified the init a bit.

**Review by raggi — APPROVED** [review]
Thanks, LGTM!

**Pull request merged**
