### PR TITLE
wgengine/filter: fix go vet failures

### PR DESCRIPTION
**Pull request by sailorfrag**
Updates #cleanup

Change-Id: I7b63daa8003159cd1b39c2ea79224c202fd6acbf

### CODE REVIEW

**Comment by bradfitz** [comment]
Where it's failing? Why didn't CI catch it?

But untagged literals are fine within a package.

**Comment by sailorfrag** [comment]
> Where it's failing? Why didn't CI catch it?

`make vet`

which also means `make check`

**Comment by sailorfrag** [comment]
```
$ git checkout origin/main
Note: switching to 'origin/main'.
HEAD is now at 781f79408 ipn/ipnlocal: allow multiple signature chains from the same SigCredential
$ make vet
./tool/go vet ./...
# tailscale.com/wgengine/filter
# [tailscale.com/wgengine/filter]
wgengine/filter/filter_test.go:771:9: tailscale.com/wgengine/filter/filtertype.PortRange struct literal uses unkeyed fields
wgengine/filter/filter_test.go:817:15: tailscale.com/wgengine/filter/filtertype.PortRange struct literal uses unkeyed fields
wgengine/filter/filter_test.go:821:15: tailscale.com/wgengine/filter/filtertype.PortRange struct literal uses unkeyed fields
wgengine/filter/filter_test.go:851:15: tailscale.com/wgengine/filter/filtertype.PortRange struct literal uses unkeyed fields
make: *** [Makefile:9: vet] Error 1
```

**Comment by sailorfrag** [comment]
Instead, I'm going to fix `make vet`, `make lint` etc match what CI is checking for.

**Pull request closed without merging**
