### PR TITLE
cmd/tailscale/cli: make up block until state Running, not just Starting

### LINKED ISSUE #2708: tailscale up should block until tailscaled is ready
In our guides for running Tailscale on serverless environments, we often use a block like this:

```sh
/app/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/var/run/tailscale/tailscaled.sock &
until /app/tailscale up --authkey=${TAILSCALE_AUTHKEY} --hostname=fly-app
do
    sleep 0.1
done
```

We do this because we need to wait for tailscaled to spin up and be ready before we pass control on to the next commands. 

We should change the default behavior of `tailscale up` to block until `tailscaled` is ready. It seems like it should have a negligible effect on the CLI experience in most cases, and would make scripting much easier.

Crawshaw warns that there are tricky edge cases and we'll need to more accurately define what "ready" looks like.

### PR DESCRIPTION
**Pull request by bradfitz**
At "Starting", the DERP connection isn't yet up. After the first netmap
and DERP connect, then it transitions into "Running".

Fixes #2708

### CODE REVIEW

**Comment by bradfitz** [comment]
I think this is right?

I don't remember why it previously waited for Starting too. Need to do some git archaeology.

**Comment by bradfitz** [comment]
The Starting or Running goes back to the first commit: a8d8b8719 ...

```go
				case ipn.Starting, ipn.Running:
					// Done full authentication process
					cancel()
				}
```

**Comment by bradfitz** [comment]
The Starting check goes back to when it was `cmd/ipn` in its very first commit: https://github.com/tailscale/corp/commit/e723ccec471004b54cd578a9dfaca2872a4e425f

```go
	bc := ipn.NewBackendClient(clientToServer)
	opts := ipn.Options{
		Prefs:      prefs,
		ServerURL:  *server,
		LoginFlags: lf,
		Notify: func(n ipn.Notify) {
			log.Printf("Notify: %v\n", n)
			if s := n.State; s != nil {
				switch *s {
				case ipn.NeedsLogin:
					bc.StartLoginInteractive()
				case ipn.NeedsMachineAuth:
					fmt.Fprintf(os.Stderr, "\nTo authorize your machine, visit (as admin):\n\n\t%s/admin/machines\n\n", *server)
				case ipn.Starting, ipn.Running:
					// Done full authentication process
					cancel()
				}
			}
			if url := n.BrowseToURL; url != nil {
				fmt.Fprintf(os.Stderr, "\nTo authenticate, visit:\n\n\t%s\n\n", *url)
			}
			if p := n.Prefs; p != nil {
				prefs = *p
				saveConfig(*config, *p)
			}
		},
	}
	bc.Start(opts)
	pump(ctx, bc, c)
```

**Review by danderson — APPROVED** [review]
Seems fine. Is there a common scenario in which we would end up stuck in Starting for legit reasons, that this would break? Offhand I can't think, but that's the only risk introduced by this change.

**Review by rosszurowski — APPROVED** [review]
Seems reasonable to me! I'd echo @danderson's concerns, but also can't think of any cases where we'd be stuck in running — and if there are some, those are bugs we should probably fix.

**Comment by tavianator** [comment]
Seems like this should fix https://github.com/tailscale/tailscale/issues/1889 as well

**Pull request merged**
