### PR TITLE
workflows: execute benchmarks

### PR DESCRIPTION
**Pull request by josharian**
#1817 removed the only place in our CI where we executed our benchmark code.
Fix that by executing it everywhere.

The benchmarks are generally cheap and fast, 
so this should add minimal overhead.

### CODE REVIEW

**Comment by bradfitz** [comment]
Windows failure looks real.

**Comment by josharian** [comment]
> Windows failure looks real.

Indeed. Which is really weird.

**Comment by josharian** [comment]
Apparently it didn't like the equals signs in `-bench=. -benchtime=1x`. Switching to `-bench . -benchtime 1x` made it happy. 🤷🏽

**Comment by bradfitz** [comment]
Really? Super skeptical. I want to understand what really happened.

**Comment by bradfitz** [comment]
Of course GitHub neither lets me look at old results, nor lets me re-run the checks on this one.

**Comment by josharian** [comment]
> Really? Super skeptical. I want to understand what really happened.

I put the equals signs back, and the test failures are back. I'll leave them here so you can look at them at your leisure. :)

**Pull request merged**
