### PR TITLE
wgengine/router/dns: use wireguard winipcfg package

### PR DESCRIPTION
**Pull request by alexbrainman**
This change replaces existing DNS setting code with

golang.zx2c4.com/wireguard/windows/tunnel/winipcfg.LUID.SetDNS
and LUID.SetDNSDomain

As suggested by Jason at

https://github.com/tailscale/tailscale/issues/1050#issuecomment-749196854

Updates #1050

Signed-off-by: Alex Brainman <alex.brainman@gmail.com>

### CODE REVIEW

**Comment by alexbrainman** [comment]
I run

make updatedeps

command. But that is obviously wrong (build failed). Please let me know how I can fix that.

I did not test this code much. But I built installer and installed TS and then run

ping hello.ipn.dev

and that works.

Feel free to reject this change, if it is not worth the trouble. But it was simple enough to implement, so I decided to do it.

Thank you.

Alex

**Comment by bradfitz** [comment]
Obviously having less unique code is better, but I think some of it was done for a reason.

Like, the `ipconfig /registerdns` I think @danderson did for some bug. I'd have to dig through the git history to remember.

In general I'd want to understand the history more before I accepted this, and understand how our paths different from upstream's paths. This is all very fiddly.

/cc @peske too.

**Comment by bradfitz** [comment]
@danderson, do we want this in for 1.6?

**Comment by bradfitz** [comment]
@danderson, did you have an opinion on this?

**Comment by bradfitz** [comment]
@danderson, can you look at this? Do you not get these emails?

**Comment by danderson** [comment]
Emails got lost, sorry.

Unfortunately, for split DNS support we need to do more stuff than winipcfg has, and the extra split DNS stuff can only be set through direct registry interaction.

Based on that, I'd say the two reasonable courses of action would be to add split-DNS functionality to winipcfg and switch to using that, or continue to do our own DNS setting.

@bradfitz @peske thoughts?

**Comment by apenwarr** [comment]
I think this PR is now obsolete? @DentonGentry @danderson

**Comment by bradfitz** [comment]
We have a Windows person starting soon. This would be a good warm-up cleanup task touching a few bits of the codebase, moving/adding stuff as needed to winipcfg.

/cc @DentonGentry

**Comment by danderson** [comment]
Was done separately.

**Pull request closed without merging**
