### PR TITLE
go.toolchain.rev: update to Go 1.20rc3

### PR DESCRIPTION
**Pull request by bradfitz**
Updates #7123

### CODE REVIEW

**Comment by bradfitz** [comment]
cc @mihaip for wasm breakage

**Comment by bradfitz** [comment]
wasm builds at least:

```
bradfitz@book1pro tailscale.com % GOOS=js GOARCH=wasm ~/src/github.com/tailscale/go/bin/go version                                         
go version go1.20rc3-ts6a17f14c05 darwin/arm64
bradfitz@book1pro tailscale.com % GOOS=js GOARCH=wasm ~/src/github.com/tailscale/go/bin/go install ./cmd/tsconnect/wasm ./cmd/tailscale/cli
bradfitz@book1pro tailscale.com % 
```

**Comment by bradfitz** [comment]
Ah, @mihaip, it fails at the wasm-opt step. On Linux:

```
bradfitz@tsdev:~/src/tailscale.com$ ./tool/go run ./cmd/tsconnect --fast-compression build
...
2023/01/30 18:58:35 ESBuild Error:
2023/01/30 18:58:35 { tailscale-wasm Cannot build main.wasm: Cannot run wasm-opt: Cannot run wasm-opt: exit status 1 0xc000edc3c0 [] Cannot build main.wasm: Cannot run wasm-opt: Cannot run wasm-opt: exit status 1}
2023/01/30 18:58:35 Build failed
```

**Comment by bradfitz** [comment]
Upgrading from binaryen 110 to 111 (the latest) also fails.

**Comment by bradfitz** [comment]
Hey @johanbrandhorst :) .... you know off the top of your head why Go 1.20 wasm output would be different enough to trip up the https://github.com/WebAssembly/binaryen wasm-opt tool?

**Comment by bradfitz** [comment]
Ah, bulk memory support was added: https://github.com/golang/go/commit/50557edf10161b1aedd3654d84a94b49bae05c43

**Review by DentonGentry — APPROVED** [review]

**Pull request merged**
