### PR TITLE
 api.md: added missing quote to POST DNS Searchpaths request body example

### PR DESCRIPTION
**Pull request by loganintech**

### CODE REVIEW

**Comment by DentonGentry** [comment]
The DCO check https://github.com/tailscale/tailscale/pull/5096/checks?check_run_id=7415674010 is looking for a Signed-off-by line in the commit message, indicating that someone signs off that the submission meets the requirements of the open source license.

Which, admittedly, is kindof silly for a PR consisting of a single quotation mark, but the robots are single-minded in their task.

The best way to address this would be in your local git client: `git commit --amend --signoff`
You don't need to make any other changes, just let it add the Signed-off-by line.

Usually one would then `git push -f` to force-push an updated change to git. Since the PR comes from a fork, I'm not entirely sure what happens when you force-push to the fork. I guess if you do so and it doesn't update here, maybe close this Pull Request and send another one where the Signed-off-by line is present.

**Comment by loganintech** [comment]
@DentonGentry looks like the force push worked, apologies for not seeing the requirement for signoff.

**Comment by loganintech** [comment]
No problem, done.

**Comment by DentonGentry** [comment]
Thanks!

**Pull request merged**
