### PR TITLE
all: upgrade to Go 1.18

### PR DESCRIPTION
**Pull request by josharian**
- wgengine/magicsock: fix goMajorVersion for 1.18 ts release
- go.mod: require Go 1.18
- go.toolchain.branch: upgrade to Go 1.18
- go.toolchain.rev: upgrade to our Go 1.18 fork
- util/netconv: add package to convert between netip and netaddr types
- wgengine/magicsock: remove final alloc from ReceiveFrom
- util/deephash: remove Tailscale toolchain compatibility shim
- ipn/ipnserver: use strings.Cut

### CODE REVIEW

**Review by bradfitz — APPROVED** [review]

**Comment by bradfitz** [comment]
Other than the CI yaml updates missing

**Comment by josharian** [comment]
I also updated the Dockerfile...but `golang:1.18-alpine` doesn't exist yet.

We have two options for breakage here:

* Break folks using the Dockerfile (base image not found), have it magically fixed when `golang:1.18-alpine` is released.
* Break folks using the Dockerfile (code doesn't compile), have to remember to fix it when `golang:1.18-alpine` is released.

I chose the former, but I'm not proud of it.

Opinions?

I also added a couple of other little 1.18-related fixes. PTAL. (It wasn't really ready the first time, I just wanted to see what CI would do with it.)

**Comment by bradfitz** [comment]
Former is fine. Life at HEAD can be a bit bumpy. The Dockerfile will come soon based on past latency.

**Review by bradfitz — APPROVED** [review]

**Comment by josharian** [comment]
GREEN AT LAST

**Comment by dsnet** [comment]
> GREEN AT LAST

🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀

**Pull request merged**
