### PR TITLE
paths: set QNAP socket to /tmp.

### PR DESCRIPTION
**Pull request by DentonGentry**
Signed-off-by: Denton Gentry <dgentry@tailscale.com>

### CODE REVIEW

**Review by bradfitz — APPROVED** [review]

**Review by bradfitz — COMMENTED** [review]
Such a weird path but 🤷

**Comment by DentonGentry** [comment]
We could move the socket to the package install directory instead of /tmp, but QNAP has a much wider variety of paths where packages might be installed. We'd need to have tailscaled fork `/sbin/getcfg Tailscale Install_Path -f /etc/config/qpkg.conf`

```
[admin@QNAP ~]$ /sbin/getcfg Tailscale Install_Path -f /etc/config/qpkg.conf
/share/CACHEDEV1_DATA/.qpkg/Tailscale
```

**Comment by bradfitz** [comment]
Can you strace that `getcfg` command? What's it do? Something we could do ourselves without the fork optimistically, only falling back to calling it if we fail to find it?

**Comment by bradfitz** [comment]
In any case, this is fine to submit for now. We can get fancier later.

**Comment by DentonGentry** [comment]
We'd have to get an strace binary onto the QNAP, it doesn't have one.
I'll submit this as it is for now.

**Pull request merged**
