### PR TITLE
derp: throttle client sends if server advertises rate limits

### PR DESCRIPTION
**Pull request by bradfitz**
derp: throttle client sends if server advertises rate limits

### CODE REVIEW

**Comment by danderson** [comment]
Sfine so far, though, we may be able to get the same result by just throttling the whole TCP connection server side, per what apenwarr was saying. I'm not sure what we'd do differently by explicitly knowing the rate limit on the client.

**Comment by bradfitz** [comment]
on the client side we can prioritize disco over data

**Comment by bradfitz** [comment]
PTAL

**Review by crawshaw — APPROVED** [review]
I believe we have a queue somewhere before this send in magicsock. If so does that make this rate limit a head drop?

**Comment by bradfitz** [comment]
> I believe we have a queue somewhere before this send in magicsock. If so does that make this rate limit a head drop?

This limiter is a head drop, between draining the magicsock queue and writing to the network. The other one is a tail drop if the queue is full, like if the write blocks in the kernel due to TCP backpressure.

**Pull request merged**
