### PR TITLE
tstime/rate: deflake TestLongRunningQPS

### PR DESCRIPTION
**Pull request by dsnet**
This test is highly dependent on the accuracy of OS timers.
Reduce the number of failures by decreasing the required
accuracy from 0.999 to 0.995.
Also, switch from repeated time.Sleep to using a time.Ticker
for improved accuracy.

Updates #2727

Signed-off-by: Joe Tsai <joetsai@digital-static.net>

### CODE REVIEW

**Comment by bradfitz** [comment]
LGTM

**Comment by bradfitz** [comment]
Feel free to `git cherry-pick -x` to the release-branch too.

**Comment by dsnet** [comment]
Done.

**Comment by josharian** [comment]
This code tracks x/time/rate pretty closely. We should probably upstream this fix there as well.

**Pull request merged**
