### PR TITLE
cmd/serve: don't convert localhost to 127.0.0.1

### PR DESCRIPTION
**Pull request by joshka**
This is not valid in many situations, specifically when running a local astro site that listens on localhost, but ignores 127.0.0.1

Fixes: https://github.com/tailscale/tailscale/issues/12201

### CODE REVIEW

**Comment by joshka** [comment]
I have a astro/starlight based website which I'd like to develop locally (https://github.com/ratatui-org/ratatui-website/). Running `npm run dev` listens on `http://localhost:4321`
Running `tailscale serve localhost:4321` changes `localhost` to `127.0.0.1`. This is not the same thing and fails.

**Comment by joshka** [comment]
ping

**Comment by bradfitz** [comment]
Change seems reasonable, but see test failures.

**Comment by joshka** [comment]
> Change seems reasonable, but see test failures.

I updated the tests that I saw, but wasn't entirely sure how to run them locally (and I wasn't sure about the impact of running these using sudo - which is what the CI does). Perhaps add something for running these to the Makefile / contributing doc?

Can you please approve the workflow to run the tests?

**Comment by joshka** [comment]
Thanks!

**Pull request merged**
