### PR TITLE
control/controlhttp: allow client and server to communicate over WebSockets

### PR DESCRIPTION
**Pull request by mihaip**
We can't do Noise-over-HTTP in Wasm/JS (because we don't have bidirectional
communication), but we should be able to do it over WebSockets. Reuses
derp WebSocket support that allows us to turn a WebSocket connection
into a net.Conn.

Updates #3157

Signed-off-by: Mihai Parparita <mihai@tailscale.com>

### CODE REVIEW

**Comment by mihaip** [comment]
Not sure what to make of the depware CI failure, the diff I have is what was generated by `./tool/go run github.com/tailscale/depaware -update tailscale.com/cmd/tailscaled`

**Comment by bradfitz** [comment]
```
bradfitz@tsdev:~/src/tailscale.com$ make updatedeps
./tool/go run github.com/tailscale/depaware --update tailscale.com/cmd/tailscaled
./tool/go run github.com/tailscale/depaware --update tailscale.com/cmd/tailscale
git bradfitz@tsdev:~/src/tailscale.com$ git di
diff --git a/cmd/tailscaled/depaware.txt b/cmd/tailscaled/depaware.txt
index 73f41043..ba0de4bc 100644
--- a/cmd/tailscaled/depaware.txt
+++ b/cmd/tailscaled/depaware.txt
@@ -79,7 +79,7 @@ tailscale.com/cmd/tailscaled dependencies: (generated by github.com/tailscale/de
         github.com/klauspost/compress/flate                          from nhooyr.io/websocket
         github.com/klauspost/compress/fse                            from github.com/klauspost/compress/huff0
         github.com/klauspost/compress/huff0                          from github.com/klauspost/compress/zstd
-        github.com/klauspost/compress/internal/cpuinfo               from github.com/klauspost/compress/zstd+
+        github.com/klauspost/compress/internal/cpuinfo               from github.com/klauspost/compress/zstd
         github.com/klauspost/compress/internal/snapref               from github.com/klauspost/compress/zstd
         github.com/klauspost/compress/zstd                           from tailscale.com/smallzstd
         github.com/klauspost/compress/zstd/internal/xxhash           from github.com/klauspost/compress/zstd
```

**Review by bradfitz — APPROVED** [review]
LGTM after the depaware fix

**Comment by bradfitz** [comment]
Do you have any dirty files in your git repo that depaware is picking up?

**Comment by bradfitz** [comment]
In the commit message, instead of `For #nnn`, use `Updates #nnnn`. (The two verbs we use for issues are "Fixes" or "Updates")

**Comment by mihaip** [comment]
It was the Go workspace, generated the correct depaware diff once I disabled it 🤷

**Pull request merged**
