### PR TITLE
wgengine/router: signal readyToEstablishVPN in SetBoth callback

### PR DESCRIPTION
**Pull request by oxtoacart**
This allows clients to avoid establishing their VPN multiple times when both routes and DNS are changing in rapid succession.

Updates tailscale/corp#18928

### CODE REVIEW

**Review by bradfitz — COMMENTED** [review]
This is making huge assumptions about how it's used by callers far far away.

A refactor in LocalBackend could easily break this.

Not to mention it contains bool parameters, my favorite :)

**Comment by oxtoacart** [comment]
What assumptions is this making? All it's doing is indicating when we're actually done reconfiguring. I suppose an alternative approach would be to only call SetBoth when we're actually done ... that might be cleaner.

**Comment by oxtoacart** [comment]
Right now, the only time we update routes without also updating DNS is when we clear them, which is a noop from the Android app's perspective. So other than something like what this PR already does, the only other thing I can think of is to introduce an explicit interface that lets wgengine explicitly signal that it's done reconfiguring, as opposed to inferring that from route and/or DNS updates.

**Comment by bradfitz** [comment]
> What assumptions is this making? 

You're assuming Set is called before SetDNS.

**Comment by oxtoacart** [comment]
Closing in favor of this [more explicity](https://github.com/tailscale/tailscale/pull/11623) version.

**Pull request closed without merging**
