### PR TITLE
ipn/ipnlocal: put a retry loop around Windows file deletes

### PR DESCRIPTION
**Pull request by bradfitz**
oh, Windows.

Updates tailscale/corp#1626

### CODE REVIEW

**Comment by apenwarr** [comment]
Didn't look at the code, but merged in the branch and tried it. Better, but not quite right.

First of all, I tried deleting the files I transferred, and one of them is apparently still being held open by tailscale-ipn.exe:

Screenshot 2021-04-22 at 12 37 29 PM

Secondly, when I transfer a batch of several files (from macOS UI), I keep getting a message of the form "We could only transfer 8 out of 9 files", which I didn't get before.

**Comment by apenwarr** [comment]
No duplicates though!

**Review by crawshaw — APPROVED** [review]
The loop looks correct even if it doesn't completely solve the problem.

**Comment by bradfitz** [comment]
Let's take the unexpected EOF diagnosis elsewhere.

I see your backend also saying: "peerapi: put Copy error: unexpected EOF".

**Pull request merged**
