### PR TITLE
derp: send new "peer gone" frames when previous sender disconnects

### PR DESCRIPTION
**Pull request by bradfitz**
Updates #150

---
This change is [Reviewable](https://reviewable.io/reviews/tailscale/tailscale/209)

### CODE REVIEW

**Comment by bradfitz** [comment]
___
*[derp/derp_server.go, line 384 at r1](https://reviewable.io/reviews/tailscale/tailscale/209#-M3-plLA1IcrUgOyOfvi:-M3-rk6p3cfFZ4ZMeDE7:bckqr9x) ([raw file](https://github.com/tailscale/tailscale/blob/d9759a22b3213885e20b63d86a7d311d161e9786/derp/derp_server.go#L384)):*
<details><summary><i>Previously, danderson (Dave Anderson) wrote…</i></summary><blockquote>

This is a blocking channel, meaning we can block the main server lock for several seconds (if sclient is currently wedged on a slow write). This seems bad. Are you sure?

Not sure how else to do this, but if we go this route I would like some expvar or logging to report stalling of the server.
</blockquote></details>

The caller use a goroutine.

**Comment by bradfitz** [comment]
@danderson, PTAL, now with magicsock changes in here too. It's untested yet, though. Passes all tests, but I haven't add enough new tests (or any varz).

I first need to re-deploy the derp servers with this before I can test it on my local tailscaleds.

**Comment by bradfitz** [comment]
Okay, now with a new varz.

**Comment by danderson** [comment]
General thought that I accidentally didn't add in reviewable: this is going to make DERP harder to debug with our current tooling. If packets are getting lost, I now don't obviously know which derp server they're supposed to transit, nor do I know the state of that derp server's routes (e.g. do we have stale routes, buggily, causing us to drop packets?).

This makes me nervous about this, vs. the fairly minor benefit I expect it to confer. What am I missing?

**Comment by bradfitz** [comment]
> General thought that I accidentally didn't add in reviewable: this is going to make DERP harder to debug with our current tooling. If packets are getting lost, I now don't obviously know which derp server they're supposed to transit, nor do I know the state of that derp server's routes (e.g. do we have stale routes, buggily, causing us to drop packets?).
>
> This makes me nervous about this, vs. the fairly minor benefit I expect it to confer. What am I missing?

I'll add logging to magicsock whenever it switches back or forth between home or alt route.

There are two main benefits:

* fewer connections (less memory for us, less radio/battery for mobile, etc)
* better latency on new connections, as the reply packet doesn't need to do 4-5 RTTs to open up a new DERP session

In any case, I'll keep it disabled in magicsock until we're happy with its debugability and see that it helps.

**Comment by danderson** [comment]
SGTM. This may be a good opportunity for a server-side feature flag as well? (so we can turn on/off from tailcontrol, do mass experiments more easily) No strong feeling though, happy to get this shipped ASAP so we can see what happens.

**Pull request merged**
