### PR TITLE
ssh/tailssh: close tty on session close

### LINKED ISSUE #8119: Each ssh connection creates a new PTS
### What is the issue?

Using tailscale ssh with an linux target creates a new TTY/PTS session even after disconnect. 
In case of a long runtime this causes some sort of exhausting/overflow of sessions and a new login is not possible any more. 

I'm not sure which logs are helpful.  

### Steps to reproduce

- Connect to host using Tailscale SSH (pts/n)
- Disconnect
- Connect to same host using Tailscale SSH 
- New Session with new/next pts (pts/n+1)

### Are there any recent changes that introduced the issue?

_No response_

### OS

Linux

### OS version

Debian 10 & 11

### Tailscale version

1.40.0

### Other software

_No response_

### Bug report

BUG-e8cd3deb76c9799e8f24f364b1415730a05d3dcb7472bc901d652139ee8853c4-20230511101031Z-a7692b90016dfd95

### PR DESCRIPTION
**Pull request by maisem**
We were only closing on side of the pty/tty pair.
Close the other side too.

Fixes #8119

cc @fritterhoff

### CODE REVIEW

**Review by bradfitz — APPROVED** [review]

**Comment by maisem** [comment]
@fritterhoff if you can confirm this works, I'll can merge it.

**Comment by maisem** [comment]
this looks like an incomplete fix, looking deeper.

**Comment by fritterhoff** [comment]
Yeah. Thats why I added some (hacky) error handling and the mutex in my PR.

**Comment by maisem** [comment]
>Yeah. Thats why I added some (hacky) error handling and the mutex in my PR.

The mutex doesn't help much sadly, as it is still a race between which copy routine acquires it first. I think what I have no works.

**Comment by fritterhoff** [comment]
Since the std out was never closed before closing the tty it looked fine for me, but prop. your solution is better 😉

**Review by bradfitz — APPROVED** [review]

**Pull request merged**
