### PR TITLE
go.mod: upgrade all deps

### PR DESCRIPTION
**Pull request by bradfitz**
At the start of a dev cycle we'll upgrade all dependencies.

Done with:

$ for Dep in $(cat go.mod | perl -ne '/(\S+) v/ and print "$1\n"'); do go get $Dep@upgrade; done

### CODE REVIEW

**Comment by josharian** [comment]
golang.zx2c4.com/wireguard/windows, but it is only used when GOOS=windows. Maybe tweak your script to hit all the major platforms?

**Comment by bradfitz** [comment]
sigh:

```
bradfitz@tsdev:~/src/tailscale.com$ GOOS=windows go get golang.zx2c4.com/wireguard/ipc/winpipe@upgrade
bradfitz@tsdev:~/src/tailscale.com$ GOOS=windows go get golang.zx2c4.com/wireguard/windows@upgrade
# golang.zx2c4.com/wireguard/windows/tunnel
../../go/pkg/mod/golang.zx2c4.com/wireguard/windows@v0.3.14/tunnel/service.go:199:10: undefined: conn.NewDefaultBind
../../go/pkg/mod/golang.zx2c4.com/wireguard/windows@v0.3.14/tunnel/service.go:200:24: too many arguments in call to device.NewDevice
../../go/pkg/mod/golang.zx2c4.com/wireguard/windows@v0.3.14/tunnel/service.go:200:57: cannot use log.Printf (type func(string, ...interface {})) as type *log.Logger in field value
../../go/pkg/mod/golang.zx2c4.com/wireguard/windows@v0.3.14/tunnel/service.go:200:69: too few values in device.Logger{...}
../../go/pkg/mod/golang.zx2c4.com/wireguard/windows@v0.3.14/tunnel/service.go:208:11: dev.IpcSet undefined (type *device.Device has no field or method IpcSet)
```

**Comment by bradfitz** [comment]
how about I let you do that part? 😂

**Comment by josharian** [comment]
Fine, fine. :P

**Review by josharian — APPROVED** [review]

**Pull request merged**
