### PR TITLE
cmd: upgrade to ffcli v3

### PR DESCRIPTION
**Pull request by josharian**
None of the breaking changes from v2 to v3 are relevant to us.

Signed-off-by: Josh Bleecher Snyder <josh@tailscale.com>

### CODE REVIEW

**Comment by bradfitz** [comment]
No benefit to us (thus only risk), so wait until 1.14 is branched.

**Comment by danderson** [comment]
Depaware sad, otherwise LGTM once 1.14 is branched

**Comment by bradfitz** [comment]
Any end-user visible changes?

**Comment by bradfitz** [comment]
We override that flag printing code anyway, so that last linked change shouldn't affect us.

**Comment by josharian** [comment]
OK, I'm going to pull the trigger on this, then.

**Pull request merged**
