### PR TITLE
wgengine/router: use quad-100 as the nexthop on Windows

### PR DESCRIPTION
**Pull request by nickkhyl**
Windows requires routes to have a nexthop. Routes created using the interface's local IP address or an unspecified IP address ("0.0.0.0" or "::") as the nexthop are considered on-link routes. Notably, Windows treats on-link subnet routes differently, reserving the last IP in the range as the broadcast IP and therefore prohibiting TCP connections to it, resulting in WSA error 10049: "The requested address is not valid in its context". This does not happen with single-host routes, such as routes to Tailscale IP addresses, but becomes a problem with advertised subnets when all IPs in the range should be reachable.

Before Windows 8, only routes created with an unspecified IP address were considered on-link, so our previous approach of using the interface's own IP as the nexthop likely worked on Windows 7.

This PR updates configureInterface to use the TailscaleServiceIP (100.100.100.100) and its IPv6 counterpart as the nexthop for subnet routes.

Fixes tailscale/support-escalations#57

### CODE REVIEW

**Comment by ramyfication** [comment]
FYI @kabirsikand  as a heads up on this edge case in Windows routing behavior.

**Review by sailorfrag — APPROVED** [review]
That's really ridiculous, but I guess I can kind of see the series of reasonable decisions on Microsoft's part that led to this.

**Comment by nickkhyl** [comment]
@kabirsikand: Nothing that I'm aware of.

**Comment by hoffmanntravis** [comment]
Great work on this Tailscale team!  Thanks for getting us relief on this issue.  That was a tricky one.

**Pull request merged**
