### PR TITLE
cmd/containerboot: use TS_EXTRA_ARGS on tailscale set instead of login

### LINKED ISSUE #9593: Tailscale docker container documentation for `TS_EXTRA_ARGS` not applying when `TS_AUTH_ONCE` is set (undocumented)
### What is the issue?

The documentation for `TS_EXTRA_ARGS` states that it takes the same settings as `tailscale set`. While trying to add a new option on boot for a container, I found the settings were not being applied at all due to having `TS_AUTH_ONCE` set.

On the [Docker container page](https://hub.docker.com/r/tailscale/tailscale) the documentation states
> TS_EXTRA_ARGS: any other CLI flags for tailscale set

And on the [Tailscale documentation reference](https://tailscale.com/kb/1282/docker/#ts_extra_args) for the container image,  it says
> Any other flags to pass in to the [Tailscale CLI](https://tailscale.com/kb/1080/cli/) in a [tailscale set](https://tailscale.com/kb/1080/cli/#set) command.

On the contrary, the [code comments](https://github.com/tailscale/tailscale/blob/32c0156311fdef2fc068d4b04ba3733527e972ec/cmd/containerboot/main.go#L22C1-L23) indicate the arguments are actually fed into `tailscale login`. While the options appear to be the similar based on Tailscale's documentation, none of these locations actually note that `TS_EXTRA_ARGS` is actualy fed into `tailscale login` and that it is not run when `TS_AUTH_ONCE` is true.

It would be great to either document this nuance or actually run `tailscale set` to permit changed settings while `TS_AUTH_ONCE` is set.

### Steps to reproduce

_No response_

### Are there any recent changes that introduced the issue?

_No response_

### OS

_No response_

### OS version

_No response_

### Tailscale version

_No response_

### Other software

_No response_

### Bug report

_No response_

### PR DESCRIPTION
**Pull request by lgo**
Previously, `TS_EXTRA_ARGS` was only used on `tailscale login`. This resulted in a  behaviour where it was implicitly not used as `tailscale login` is only run when authenticating for the first time if `TS_AUTH_ONCE` is set (now defaulted).

After, `TS_EXTRA_ARGS` is used on each launch via the `tailscale set` that occurs after tailscale is running. This allows for the expected customization that this argument is documented as.

Resolves #9593, #9809

Note, I still need to test this to ensure it doesn't break other behaviour. This change will represent a meaningful change to the behaviour of the Docker env arguments, but one that better aligns to the expected and documented behaviour.

### CODE REVIEW

**Review by maisem — COMMENTED** [review]
This isn't the right fix. This means that other flags like login-server and advertise-tags won't work because they are only relevant for tailscale login and not tailscale set.

**Comment by lgo** [comment]
I see. Back when I last took a look, tailscale was using `tailscale up` and the arguments were similar but that's now no longer the case with `tailscale login`.

What do you think would be the most appropriate way to address this? Two separate env variables? Command parsing, to separate out the `tailscale login` arguments? Something else?

**Comment by maisem** [comment]
> I see. Back when I last took a look, tailscale was using `tailscale up` and the arguments were similar but that's now no longer the case with `tailscale login`.
> 
> What do you think would be the most appropriate way to address this?
> 
> * Two separate env variables? This would be a nasty incompatibility for Docker upgrades, if the existing one is renamed, unless a new one is added and `TS_EXTRA_ARGS` is left as login-specific which would be confusing naming

Yeah, we could add something like `TS_SET_EXTRA_ARGS`.

> * Command parsing to separate out the `tailscale login` arguments? This seems rather complex and brittle solution unless we can just re-use the existing command parsers here to do that.

This is brittle, I agree we would need to refactor the command parsers to share the logic.

**Comment by maisem** [comment]
or https://github.com/tailscale/tailscale/pull/9814

**Comment by lgo** [comment]
Awesome, thanks for addressing the issue in the most appropriate way!

**Pull request closed without merging**
