### PR TITLE
cmd/tailscale: add ip -1 flag

### PR DESCRIPTION
**Pull request by josharian**
- cmd/tailscale: improve ip subcommand docs
- cmd/tailscale: add ip -1 flag

### CODE REVIEW

**Comment by josharian** [comment]
If this goes in, where do I put release notes?

**Review by bradfitz — APPROVED** [review]

**Comment by bradfitz** [comment]
> And we do we have a general process for remembering to update docs (to use this new flag) after a new release?

We've started to sometimes do the whole RELNOTE= thing in the commit mesage.

**Comment by DentonGentry** [comment]
If you put `RELNOTE=tailscale ip adds a -1 flag` in the commit message, we'll pick it up in the release notes (it is a manual process so a human does look at it before it goes in).

If that RELNOTE message also mentions other docs to update, we're likely to do so.

**Comment by josharian** [comment]
Added RELNOTE. Thanks.

**Pull request merged**
