### PR TITLE
tempfork: temporarily fork gliderlabs/ssh and x/crypto/ssh

### PR DESCRIPTION
**Pull request by bradfitz**
While we rearrange/upstream things.

Updates #3802

### CODE REVIEW

**Review by maisem — COMMENTED** [review]
I don't see the crypto ssh fork

**Comment by bradfitz** [comment]
Where'd you look? Because it's at the same as its Go import path would suggest: https://github.com/tailscale/golang-x-crypto

**Comment by bradfitz** [comment]
Oh, you only looked at the files changed.

See the commit message text: https://github.com/tailscale/tailscale/pull/4291/commits/5567039434ad0014e99b40585ffef76b449c84dd

**Review by maisem — APPROVED** [review]
Ah, sorry I was looking at the first message in the PR.

**Pull request merged**
