### PR TITLE
ipn/ipnlocal: update routes on link change with ExitNodeAllowLANAccess

### PR DESCRIPTION
**Pull request by raggi**
On a major link change the LAN routes may change, so on linkChange where ChangeDelta.Major, we need to call authReconfig to ensure that new routes are observed and applied.

Updates tailscale/corp#22574

### CODE REVIEW

**Review by bradfitz — APPROVED** [review]

**Comment by bradfitz** [comment]
Good thing natlab isn't more done, otherwise I'd ask for a new test for this 😉

**Comment by raggi** [comment]
> Good thing natlab isn't more done, otherwise I'd ask for a new test for this 😉

I'd actually love to, I don't want to merge until I've at least done a manual test. I'd love to be typing one!

**Comment by raggi** [comment]
Created a test case in a VM, adding and removing a 192.168.90/24 subnet route, observed unable to ping a peer adding the route with current stable, able to add a route and then ping the peer with this build.

```
monitor: RTM_NEWROUTE: src=192.168.90.2/0, dst=192.168.90.255/32, gw=, outif=2, table=255
linkChange: in state Running; updating LAN routes
```

**Comment by raggi** [comment]
Discovered new, independent and pre-existing but slightly related bug while testing: https://github.com/tailscale/tailscale/issues/13263

**Pull request merged**
