### PR TITLE
cmd/tsconnect: export IPNNetMap types in ts package

### PR DESCRIPTION
**Pull request by twitchyliquid64**
No idea if I'm doing this right?

### CODE REVIEW

**Comment by twitchyliquid64** [comment]
Sweet - think that worked

**Comment by mihaip** [comment]
CI passed, but did it actually export the type in the `pkg.d.ts` file? I don't see it when I patch in your change.

Will play around with this, but I think implementing the alternate suggestion from https://github.com/tailscale/corp/pull/10110#discussion_r1151047339 might be the better overall solution.

**Comment by mihaip** [comment]
Actually, I don't think you need this change at all. The type definition already says:

```typescript
declare global {
  ...
  type IPNNetMap = { ... }
}
```

So it's already known in the global scope. You should be able to use it without any `import` on the corp repo side.

**Comment by twitchyliquid64** [comment]
Gotcha - will try that in the other PR!

**Pull request closed without merging**
