### PR TITLE
cmd/tailscale/cli: Add CLI command to update certs on Synology devices.

### LINKED ISSUE #4674: FR: Automatically configure Synology with `tailscale cert` in Settings : Security/Certificate
### What are you trying to do?

I want to secure my Synology NAS (model: `DS920+`) via HTTPS endpoint. I'm using Synology DSM version: `DSM 7.0.1-42218 Update 3.` 

Synology allows users to specify their own certs. You can find more information here: https://kb.synology.com/en-nz/DSM/help/DSM/AdminCenter/connection_certificate?version=7

I successfully secured my NAS by using Tailscale certs. The steps I've done:

1. Enable SSH on my Synology
2. SSH into the machine and run `sudo tailscale cert my-domain`
3. Copy the files somewhere I could download to my MacBook (that's needed unfortunately as Synology can't select a cert from its own disk)
4. Go to the `Security/Certificate` section and add a new certificate
5. After adding the certificate, make sure to click on `Settings` in the `Security/Certificate` tab to use the new certificate:

ScreenShot-2022-05-14-at-00 52 36@2x

The final result on the `Security/Certificate` tab should look like:

ScreenShot-2022-05-14-at-00 34 20@2x

After these steps, I could visit my Synology home page and could verify that HTTPS work out of the box:

ScreenShot-2022-05-14-at-00 36 36@2x

### How should we solve this?

It would be dope if the Synology Tailscale application could automatically generate and add the certificate to the settings. After that, the users could go to the `Security/Certificate` tab and enable the certificate for the services they are interested in. 

### What is the impact of not solving this?

It's cumbersome to set up HTTPS for Synology NAS, see the above steps.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by WillMorrison**
Fixes #4674

### CODE REVIEW

**Comment by WillMorrison** [comment]
A note about testing: I do not have a Synology device that I can install a new version of tailscale on to test this. I have tested that the commands used by this code work on my Synology device, but since the only access I have to it is via tailscale, I don't want to risk losing that access by reinstalling the tailscale package. If there are Synology devices that could be used to test this new command on (with different DSM versions perhaps), please let me know how to go about doing that testing.

**Comment by WillMorrison** [comment]
@sailorfrag Could you please let me know what is needed to get this PR reviewed and merged?

**Comment by sailorfrag** [comment]
I'm not able to test out Synology changes because I don't have any devices but I've asked internally for someone to take a look

**Comment by WillMorrison** [comment]
@sailorfrag This PR seems to have fallen through the cracks again. @sailorfrag can you let me know who was doing the testing so I can follow up with them directly?

**Comment by WillMorrison** [comment]
@bradfitz @danderson This PR has gotten no review for over 2 months now. Please let me know who is responsible for reviewing open source contributions to tailscale, (or better yet update the contributions section of the README), so that I don't have to ping the fine members of the Tailscale GitHub org at random hoping for a response. :)

**Review by bradfitz — APPROVED** [review]
Looks great, thanks!

**Comment by jovobe** [comment]
Thanks so much for merging this! I've waited a long time for this 🙏🏻 But just to things right: This is not included in 1.64.0, right? When will this be released?

**Comment by bradfitz** [comment]
It's in 1.64.0.

**Comment by jovobe** [comment]
I'm on 1.64.0 (Synology DSM 7.2.1-69057 Update 4) and the subcommand does not exist. What am I soing wrong?

```
ash-4.4# tailscale synology-cert
The easiest, most secure way to use WireGuard.

USAGE
  tailscale [flags] <subcommand> [command flags]

For help on subcommands, add --help after: "tailscale status --help".

This CLI is still under active development. Commands and flags will
change in the future.

SUBCOMMANDS
  up              Connect to Tailscale, logging in if needed
  down            Disconnect from Tailscale
  set             Change specified preferences
  login           Log in to a Tailscale account
  logout          Disconnect from Tailscale and expire current node key
  switch          Switches to a different Tailscale account
  configure       [ALPHA] Configure the host to enable more Tailscale features
  netcheck        Print an analysis of local network conditions
  ip              Show Tailscale IP addresses
  status          Show state of tailscaled and its connections
  ping            Ping a host at the Tailscale layer, see how it routed
  nc              Connect to a port on a host, connected to stdin/stdout
  ssh             SSH to a Tailscale machine
  funnel          Serve content and local servers on the internet
  serve           Serve content and local servers on your tailnet
  version         Print Tailscale version
  web             Run a web server for controlling Tailscale
  file            Send or receive files
  bugreport       Print a shareable identifier to help diagnose issues
  cert            Get TLS certs
  lock            Manage tailnet lock
  licenses        Get open source license information
  exit-node       Show machines on your tailnet configured as exit nodes
  update          Update Tailscale to the latest/different version
  whois           Show the machine and user associated with a Tailscale IP (v4 or v6)
  drive           Share a directory with your tailnet
  configure-host  Configure Synology to enable outbound connections

FLAGS
  --socket string
    	path to tailscaled socket (default /var/packages/Tailscale/var/tailscaled.sock)
```

```
ash-4.4# tailscale --version
1.64.0
  tailscale commit: 7e9bebdb2470dfbb6e08a3f12a289a7d88128dfb
  other commit: f314c5be5350431460b89f703275de6b89a30460
  go version: go1.22.2
```

**Comment by bradfitz** [comment]
It's a configure subcommand: `tailscale configure synology-cert`

**Comment by cheesegrits** [comment]
@WillMorrison thank you for your persistence in getting this merged. :)

Couple of quick questions.

Is this analag to a certbot renew, in that I should run it twice a day and it will only renew a cert when needed, or should I only run it every 90 days?

Does the API call that uploads the cert trigger a restart / reload of services configured in DSM to use it?

**Comment by WillMorrison** [comment]
> Is this analogous to a certbot renew, in that I should run it twice a day and it will only renew a cert when needed, or should I only run it every 90 days?

I believe that tailscale [caches certificates](https://github.com/tailscale/tailscale/blob/964282d34f06ecc06ce644769c66b0b31d118340/client/tailscale/localclient.go#L853) and won't request a new one if the old one is still valid.
 
> Does the API call that uploads the cert trigger a restart / reload of services configured in DSM to use it?

I know the DSM will restart the web server, but I have no idea if anything else will happen for services that are configured to use the cert.

**Comment by galettof** [comment]
I came across this discussion while looking for ways to renew certificates that are used with Tailscale on synology NAS. I report on my experience hoping it might help others.

I set up a task to run `tailscale configure synology-cert`. Maybe it is because I set it to run as root, but it didn't do anything until I added `sudo` in front; after that it renewed the certificate as expected.

After renewal, the login page for the NAS immediately worked. Synology Drive (for syncing files between computer and NAS) also worked right away. However, Hyperbackup (that I use to back up one NAS to another) did not work until I restarted both units; before restarting I was getting an error that the target for the backup was offline and when trying to reconnect it said failed to reach destination.

**Comment by sim642** [comment]
> I set up a task to run `tailscale configure synology-cert`. Maybe it is because I set it to run as root, but it didn't do anything until I added `sudo` in front; after that it renewed the certificate as expected.

It worked for me for the `root` user without `sudo` in the scheduled task user-defined script.

For some reason the new command is nowhere documented (except for this PR), so I wrote my own guide here: https://sim642.eu/blog/2024/08/11/tailscale-https-certificate-on-synology-nas/. Hopefully, it also gets mentioned in the official Tailscale documentation at some point.

**Comment by rory-brenan** [comment]
> > I set up a task to run `tailscale configure synology-cert`. Maybe it is because I set it to run as root, but it didn't do anything until I added `sudo` in front; after that it renewed the certificate as expected.
> 
> It worked for me for the `root` user without `sudo` in the scheduled task user-defined script.
> 
> For some reason the new command is nowhere documented (except for this PR), so I wrote my own guide here: https://sim642.eu/blog/2024/08/11/tailscale-https-certificate-on-synology-nas/. Hopefully, it also gets mentioned in the official Tailscale documentation at some point.

Hi Simmo, unfortunately your guide didn't work for me... any further pointers? I have detailed my steps so far [on reddit](https://www.reddit.com/r/Tailscale/comments/1eru920/generate_tls_for_synology_nas/?).

**Comment by sim642** [comment]
The output sounds like you might need to update Tailscale on your Synology because it doesn't seem to have the `synology-cert` configuration command.

**Comment by mback2k** [comment]
There is currently also an issue with the certificate generated, please see: https://github.com/tailscale/tailscale/issues/12762

**Pull request merged**
