### PR TITLE
wgengine/magicsock: improve/fix peermap.upsertEndpoint

### PR DESCRIPTION
**Pull request by josharian**
- wgengine/magicsock: fix typo in comment
- wgengine/magicsock: fix bug in peerMap.upsertEndpoint
- wgengine/magicsock: simplify peerMap.upsertEndpoint

### CODE REVIEW

**Comment by josharian** [comment]
Three commits. First is trivial, second is a meaningful bug fix with no test, last is cleanup and can be happily ignored if desired.

The testing plan for the second commit is probably to finish up the `validate` function in josh/peermap, combined with the stress test in bradfitz/1_16_stress_netmap.

**Comment by josharian** [comment]
CI failure is https://github.com/tailscale/tailscale/issues/3289

**Review by bradfitz — APPROVED** [review]
I'd be more enthusiastic about approving the commit (2) with no test if the stress test commit were ready (or part of this PR).

But I'll trust your ordering.

**Comment by josharian** [comment]
I'll do the validation and stress test next, pinky promise.

**Pull request merged**
