### PR TITLE
ipnlocal: fix sync.Cond-related test flakiness

### PR DESCRIPTION
**Pull request by josharian**
- Revert "ipn/ipnlocal: remove locks around sync.Cond.Broadcast call"
- ipn/ipnlocal: add LocalBackend.broadcastStatusChanged

### CODE REVIEW

**Comment by bradfitz** [comment]
https://pkg.go.dev/sync#Cond.Broadcast says:

> It is allowed but not required for the caller to hold c.L during the call.

So why does this fix things? Add some comments to the code so it's not reverted?

**Comment by josharian** [comment]
I don't know. I'm happy to investigate more, but I'd like to get at least the revert submitted right away, to get the build stable again. You OK with that?

**Comment by josharian** [comment]
> So why does this fix things? Add some comments to the code so it's not reverted?

The deadlock occurs in the Wait call here:

```go
// Requests the wgengine status, and does not return until the status
// was delivered (to the usual callback).
func (b *LocalBackend) requestEngineStatusAndWait() {
	b.logf("requestEngineStatusAndWait")

	b.statusLock.Lock()
	go b.e.RequestStatus()
	b.logf("requestEngineStatusAndWait: waiting...")
	b.statusChanged.Wait() // temporarily releases lock while waiting
	b.logf("requestEngineStatusAndWait: got status update.")
	b.statusLock.Unlock()
}
```

If the call to `go b.e.RequestStatus()` completes all of its work, including calling `b.statusChanged.Broadcast()` before we reach the `b.statusChanged.Wait()` line, then no one ever unblocks the waiter.

With the calls to Lock, though, the call to Broadcast cannot occur until the waiter is blocked in the wait.

It's not pretty, but it works. I'll add a comment.

**Comment by josharian** [comment]
PTAL

**Review by bradfitz — APPROVED** [review]

**Pull request merged**
