### PR TITLE
control/controlclient: avoid crash sending map request with zero node key

### LINKED ISSUE #1271: macOS: client crash
Partial stacks recovered the hard way from logs:

```
panic: Tried to generate emptyPrivate.Public()
goroutine 382 [running]:
    tailscale.com/types/wgkey.(*Private).Public(0xc0003e3a90, 0x0, 0x0, 0x0, 0x0)
    tailscale.com@v0.0.0-00010101000000-000000000000/types/wgkey/key.go:169 +0x12f
    tailscale.com/control/controlclient.(*Direct).sendMapRequest(0xc0002d6000, 0x1051bb9c0, 0xc00069ab40, 0x1, 0x0, 0x0, 0x0)
```

### PR DESCRIPTION
**Pull request by bradfitz**
Fixes #1271

### CODE REVIEW

**Review by crawshaw — APPROVED** [review]
It's definitely right to avoid a panic here, but do you have any sense as to how we try to do a map request without a node key? Seems really weird the client hasn't generated one before the request.

**Comment by bradfitz** [comment]
@crawshaw, I think it started when I added the lite endpoint handler (and added `sendNewMapRequest`). See my second push after your approval. Previously the sole caller checked c.loggedIn before doing the direct.PollNetMap call. The new path I added didn't enforce that invariant. Now it does, so it's fixed on both sides.

But customer bug https://github.com/tailscale/felicity/issues/4 also has a macOS IPNExtension crash, but with 1.2.4. I'm looking at logs now (with `-r`) to see what that might've been. It might've been something else, as this code path was new in 1.4.

**Comment by bradfitz** [comment]
Will wait to submit (+backport) until others confirm it makes sense.

**Comment by crawshaw** [comment]
Explanation makes sense to me! (Will be curious to see what the corp controlclient tests say.)

**Comment by bradfitz** [comment]
> Will be curious to see what the corp controlclient tests say.

```
$ ./do ./control/controlclient/test
redo  control/controlclient/test
redo    (../../go.toolchain.cmd)
redo    check-redo-dirs
redo  control/controlclient/test (resumed)                                                                                                                                                 
ok      tailscale.io/control/controlclient      0.375s
```

**Comment by bradfitz** [comment]
Okay, merged in main and release branch.

**Comment by crawshaw** [comment]
Note that you merged it into the oss release branch, but not the corp submodule release branch.

**Comment by bradfitz** [comment]
Yes, that's what I usually do until it's time for a release.

**Pull request closed without merging**
