### PR TITLE
wgengine/filter: let unknown IPProto match if IP okay & match allows all ports

### PR DESCRIPTION
**Pull request by bradfitz**

### CODE REVIEW

**Review by crawshaw — APPROVED** [review]
While here, should we add some more obscure protos to this filter?

**Comment by bradfitz** [comment]
Like what? This covers all protocols. You want port parsers for certain ones? Which?

**Comment by tinoue** [comment]
Excellent solution. Thaks!

**Comment by amosbird** [comment]
Hmm, with this PR I still cannot make ipip or gre tunnel work under two tailscale endpoints. Do I need special configuration?

**Comment by DentonGentry** [comment]
An ACL rule allowing `"dst": "something:*"` is expected to allow IPinIP and GRE through. If that isn't working please open an issue, we may not notice comments on closed pull requests.

**Pull request merged**
