### PR TITLE
cmd/tailscale: provide a better error message when tailscaled isn't running

### LINKED ISSUE #2797: cmd/tailscale: provide a better error message when tailscaled isn't running
On my mac, when I run `tailscale ip` while Tailscale isn't running, I get the following error:

```
$ tailscale ip -6
2021/09/05 10:49:08 Get "http://local-tailscaled.sock/localapi/v0/status": dial tcp [::1]:51946: connect: connection refused
```

As a new user, I'd have no clue what this means. If we fail to connect to the local tailscaled socket, let's wrap the error in something more human readable that hits the following points:

- Tailscaled is not running
- You can start tailscaled by doing X
- You can find more information at Y (url)

### PR DESCRIPTION
**Pull request by bradfitz**
Fixes #2797

### CODE REVIEW

**Review by rosszurowski — COMMENTED** [review]
Trying this out on macOS, I'm getting this:

```
$ go run ./cmd/tailscale --socket=/tmp/ts/ts.sock up
failed to connect to local Tailscale service; is Tailscale running?
exit status 1
```

And this

```
$ go run ./cmd/tailscale --socket=/tmp/ts/ts.sock ip -4
Get "http://local-tailscaled.sock/localapi/v0/status": safesocket: failed to connect to /tmp/ts/ts.sock: dial unix /tmp/ts/ts.sock: connect: no such file or directory; failed to connect to Tailscale IPNExtension: failed to run '/usr/sbin/lsof -n -a -u501 -c IPNExtension -F' looking for IPNExtension: exit status 1
```

Neither of which seem to be using the changes in your code. Am I holding it wrong?

**Comment by bradfitz** [comment]
Ah, there was already a prior attempt at this used in some places. Moving/unifying them.

**Comment by bradfitz** [comment]
PTAL

**Review by rosszurowski — APPROVED** [review]
Nice.

Some of the details about eg. IPNExtension on macOS probably aren't a ton of help to users, and muddy up the core useful info in the message: _"is Tailscale running?"_

Consider this PR's error vs. the following (for macOS):

```console
# PR
$ go run ./cmd/tailscale --socket=/tmp/ts/ts.sock up
failed to connect to local Tailscale service or extension; is Tailscale running? No IPNExtension process and dial unix /tmp/ts/ts.sock: connect: no such file or directory
exit status 1

# Proposed
$ go run ./cmd/tailscale --socket=/tmp/ts/ts.sock up
Failed to connect to the local Tailscale service or extension.
Ensure the Tailscale app is running.
exit status 1
```

It's just an example — it doesn't cover the 3 ways of running Tailscale on macOS — but as an end user, `/tmp/ts/ts.sock: connect: no such file or directory` isn't _suuper_ helpful to me.

Overall though, I get why we'd want to keep some useful info around in case users are reporting bugs, or for more technical users who can troubleshoot. And this is definitely a step up from the crazy localapi error before.

So I say, :ship: ship it

**Pull request merged**
