### PR TITLE
wgengine/netstack: close forwarded TCP connections when incoming TCP dies

### PR DESCRIPTION
**Pull request by bradfitz**
Updates #4522

### CODE REVIEW

**Comment by bradfitz** [comment]
@raggi, is this right?

When does the `notifyCh` fire from here:

```
waitEntry, notifyCh := waiter.NewChannelEntry(waiter.EventHUp) // TODO(bradfitz): right EventMask?
```

**Review by DentonGentry — APPROVED** [review]
LGTM to me, it will let it not be blocked waiting for a <-connClosed which will never come.

**Comment by bradfitz** [comment]
I'm just not sure when `notifyCh` fires so I'm afraid it might be too soon and break active connections.

**Comment by raggi** [comment]
> waiter.NewChannelEntry(waiter.EventHUp)

This is essentially the same as POLLHUP so a relatively catch-all for disconnection, but it does not imply EOF (more on that below). It is the right signal.

Good catch, this is a subtle case where not enough data is flowing to cause a teardown from the data plane.

I'm wary of dropping tail buffers due to the eager closes. Right now I think because this is dropping out in the fall-back path in io.Copy it's not trivial to do much better, but it would be better to follow a shutdown path on hup, but it's a little more tricky to plumb as either we need to wire up server read shutdown on client hup notify in order to guarantee a clean overall shutdown path, assuming dropped packets and naïve copy.

**Comment by bradfitz** [comment]
@raggi, what about adding `time.Sleep(2 * time.Second) // wait for pending copies to maybe finish 🤪 `?  

Is that effectively what you mean? We can `shutdown` (er, https://pkg.go.dev/net#TCPConn.CloseWrite) one of the parts and wait for the io.Copy to close on its own?

**Comment by raggi** [comment]
I believe that there is a possible condition to fix here, and having reviewed it in more detail I think there might also be some code paths in netstack that aren't always signalling wake-up when we might need them to. Despite this, I was unable to reproduce _this condition_ using any obvious methods, so I'd like to revisit this with a finer toothcomb before we land changes. For posterity, a patch implementing the wordy thing I was suggesting above is https://github.com/tailscale/tailscale/commit/19defaf6dd292cf5fe021f092d2fe642a1d98877, though similarly I'm not sure this is strictly necessary and want to go through the netstack behavior carefully or produce a functional test to demonstrate the need.

**Comment by bradfitz** [comment]
I forget the context here. Closing.

**Pull request closed without merging**
