### PR TITLE
syncs: add MutexValue

### PR DESCRIPTION
**Pull request by dsnet**
MutexValue is simply a value guarded by a mutex.
For any type that is not pointer-sized,
MutexValue will perform much better than AtomicValue since it will not incur an allocation boxing the value into an interface value (which is how Go's atomic.Value is implemented under-the-hood.

Updates #cleanup

### CODE REVIEW

**Review by scottjab — APPROVED** [review]

**Comment by dsnet** [comment]
I added some documentation to guide when to use `MutexValue` or `AtomicValue` or `atomic.Pointer`. I've reasoned myself into thinking that `AtomicValue` should rarely be used and be replaced by either `atomic.Pointer` or `MutexValue`.

**Comment by bradfitz** [comment]
I object (as usual :)) to `#cleanup`. Especially for new API. Why? http://go/cleanup

**Review by bradfitz — COMMENTED** [review]
Code itself is fine, though :)

**Comment by dsnet** [comment]
Doesn't this somewhat fall under:

> moving away from deprecated API to equivalently behaving newer API

We're not going to deprecate AtomicValue, but I'm looking at many of the use cases and they would be better suited using `MutexValue`.

**Pull request merged**
