### PR TITLE
cmd/derper: record TLS versions used for requests.

### PR DESCRIPTION
**Pull request by danderson**
Surveying the fleet prior to turning off old/unused/insecure
TLS versions.

Updates tailscale/corp#3615

Signed-off-by: David Anderson <danderson@tailscale.com>

### CODE REVIEW

**Review by bradfitz — APPROVED** [review]
LGTM but also interesting would be active sessions broken down by TLS version in addition to just new connection counters if you want to also add that.

That'd tell us the difference between e.g. some buggy/old scrapper hitting us a bunch that's not actually a DERP client.

**Comment by danderson** [comment]
Hmm, possibly. I copied this code over from our other server, since right now I suspect the answer is 0.0qps for both TLS 1.0 and 1.1, and I didn't want to make something custom if that's all that happens.

Would you care about tracking TLS version in the long term, rather than as a one-off now? If so, I can make it session-based.

**Comment by bradfitz** [comment]
> Would you care about tracking TLS version in the long term, rather than as a one-off now? If so, I can make it session-based.

Yeah, long term would be interesting, to watch TLS 1.3 adoption over time. At some point we may want to lock/ratchet it. It should always be 1.3 if there's no MITM. I want to see what percent of active sessions are corp-MITM'ed.

**Comment by danderson** [comment]
Done, PTAL. Now have a gauge-per-version for active requests, and a per-request counter for seeing any short-lived requests.

**Review by bradfitz — APPROVED** [review]

**Pull request merged**
