### PR TITLE
cmd/tailscale/cli: these features do actually work, at least on my synology ds220j

### PR DESCRIPTION
**Pull request by Xe**
Tested on my local synology.

Ref: https://app.frontapp.com/open/cnv_fxe8zf5

Signed-off-by: Christine Dodrill <xe@tailscale.com>

### CODE REVIEW

**Review by crawshaw — COMMENTED** [review]
I assume --accept-routes is using the hybrid netstack? If so, great.

I'm unsure about removing the --netfilter-mode check though. Is that necessary for some feature? I fear it may be broken someplaces.

**Comment by Xe** [comment]
Subnet routes won't work without it :/

**Review by crawshaw — APPROVED** [review]
OK it looks like the default for synology is off because of this bug: https://github.com/tailscale/tailscale/issues/451

Do you not see any of those error messages when you turn netfilter mode to on? If not, I suppose it's ok to let users try to turn it on, as the default is off.

**Comment by bradfitz** [comment]
The lines being deleted were more a statement of policy: we didn't intend to support iptables mode on Synology, nor accepting routes. Only netstack mode for inbound traffic. Iptables on Synology is too inconsistent/unavailable/weird to depend on or be worth trying to support.

Until we understand Synology better and have a fleet of various types/versions with automated test coverage, I'd feel nervous trying to claim it's supported.

**Pull request closed without merging**
