### PR TITLE
util/httpm, all: add a test to make sure httpm is used consistently

### PR DESCRIPTION
**Pull request by bradfitz**
Updates #cleanup

### CODE REVIEW

**Comment by andrew-d** [comment]
```
=== RUN   TestUsedConsistently
    httpm_test.go:27: http.MethodFoo constant used in util/httpm/httpm_test.go; use httpm.FOO instead
--- FAIL: TestUsedConsistently (0.04s)
```

**Comment by bradfitz** [comment]
@andrew-d, hey, it worked until I `git add`ed the test 🤪

**Review by andrew-d — APPROVED** [review]

**Comment by ajhalili2006** [comment]
> ```
> === RUN   TestUsedConsistently
>     httpm_test.go:27: http.MethodFoo constant used in util/httpm/httpm_test.go; use httpm.FOO instead
> --- FAIL: TestUsedConsistently (0.04s)
> ```

I'm also experiencing the same issue while packaging `v1.54.0` for Alpine Linux ([see merge request](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/55922))

**Comment by andrew-d** [comment]
> > ```
> > === RUN   TestUsedConsistently
> >     httpm_test.go:27: http.MethodFoo constant used in util/httpm/httpm_test.go; use httpm.FOO instead
> > --- FAIL: TestUsedConsistently (0.04s)
> > ```
> 
> I'm also experiencing the same issue while packaging `v1.54.0` for Alpine Linux ([see merge request](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/55922))

@ajhalili2006 I'm not familiar with how Alpine packaging works... is there an easy way for me to run the tests in the same way as that merge request did, so I can debug things locally?

**Comment by andrew-d** [comment]
@ajhalili2006 Could you see if https://github.com/tailscale/tailscale/pull/10363 helps here? It's a bit tricky to tell exactly what the failure is, but I note that the archive you're fetching during the build doesn't contain the `.git` directory, which might cause this?

**Comment by ajhalili2006** [comment]
> @ajhalili2006 Could you see if #10363 helps here? It's a bit tricky to tell exactly what the failure is, but I note that the archive you're fetching during the build doesn't contain the `.git` directory, which might cause this?

It worked! Thanks @andrew-d, will backporting fix soon.

**Pull request merged**
