### PR TITLE
workflows: run staticcheck on more platforms

### PR DESCRIPTION
**Pull request by josharian**

### CODE REVIEW

**Comment by josharian** [comment]
Blocked on #1841 so that the newly added CI will pass.

**Comment by josharian** [comment]
Fixing the freebsd failure runs into https://github.com/godbus/dbus/issues/237. :/ Waiting for that to get fixed upstream.

**Comment by josharian** [comment]
The freebsd thing is because it requires cgo to build. Not worth fighting; removed. The big three is enough for now.

**Comment by DentonGentry** [comment]
So presumably MacOS also substantially covers iOS, and we can revisit Android and Synology later.

**Review by DentonGentry — APPROVED** [review]

**Comment by josharian** [comment]
Sadly, iOS has the same "requires cgo" issue that freebsd has.

**Pull request merged**
