### PR TITLE
tailcfg: add StableID to Node.

### PR DESCRIPTION
**Pull request by danderson**

### CODE REVIEW

**Review by bradfitz — APPROVED** [review]

**Comment by josharian** [comment]
I thought the plan was to start returning stable IDs in the ID field. (Once we have stable IDs to return, there’s no reason not to use the ID field.) But maybe I misunderstood some part of the discussion.

**Comment by danderson** [comment]
We can't change the type of the field named ID on the wire if we have to keep supporting old clients, the JSON decode will fail. Strictly speaking we could vary the structure of tailcfg.Node based on a MapRequest version, but that seems fraught compared to creating a new field and deleting the old one once the transition is complete?

**Comment by danderson** [comment]
We can talk options more tomorrow as well if you'd like, I'm out for today so happy to hold off and figure things out.

**Comment by bradfitz** [comment]
@danderson's change is what I remember the decision being from the meeting today.

**Comment by josharian** [comment]
Let’s discuss tomorrow. There’s a good option available.

**Comment by bradfitz** [comment]
> Let’s discuss tomorrow. There’s a good option available.

a new type that implements json.Marshaler etc into different JSON types based on its value? 😂

**Comment by danderson** [comment]
After discussion: we're doing this.

**Pull request merged**
