### PR TITLE
Compatible with the new wireguard-go

### PR DESCRIPTION
**Pull request by peske**
Uses the new version of [https://github.com/tailscale/wireguard-go/](https://github.com/tailscale/wireguard-go/tree/ap/tailscale-main-rebase). Adapts to some changes in `wireguard-go` API. The key change is that there's no more `NativeTun.GUID()` method in the new `wireguard-go`.

### CODE REVIEW

**Comment by peske** [comment]
Regarding some failed workflows: it looks that some tests are failing because there's no `WinTun.dll` available (which is needed to run the latest `wireguard-go`).
There are also some `depaware` errors that I don't understand yet.

**Comment by bradfitz** [comment]
See the `Makefile` for depaware. (https://github.com/tailscale/depaware)  Run `make updatedeps` to update the files so the CI will pass.

**Comment by bradfitz** [comment]
> some tests are failing because there's no WinTun.dll available

The CI yaml files (or some tests) will need to be updated to download the wintun.dll on demand from somewhere.

One option I do sometimes is submit the binary (DLL or whatever) to a branch and then use git to download it. (If you've got 7 minutes, I talk about it in https://www.youtube.com/watch?v=69Zy77O-BUM)

**Comment by josharian** [comment]
This looks plausible, but I'd like to re-review once we've upstreamed what we need to x/sys/windows/registry, per Brad's comment above.

**Comment by alexbrainman** [comment]
> but I'd like to re-review once we've upstreamed what we need to x/sys/windows/registry, per Brad's comment above.

@peske if you need help up-streaming changes to golang.org/x/sys/windows, I am happy to do it. Please, discuss here what do you think we can submit, and I can do it.

Thank you.

Alex

**Comment by josharian** [comment]
@alexbrainman thanks. I believe that https://go-review.googlesource.com/c/sys/+/277152 is what we need upstream.

**Comment by peske** [comment]
Hey @alexbrainman! Thank you very much for offering help!

To be honest, I don't know too much about https://go-review.googlesource.com/c/sys/+/277152, so I'll have to take a look there first. Will let you know.

Thanks!

Aleks :)

**Comment by peske** [comment]
Oh, I've just found out that it's already done (it's already in x/sys/windows master). Thanks!

I'm closing this PR, and I'll create a new one (with cleaner history) in minutes.

**Pull request closed without merging**
