### PR TITLE
cmd/microproxy: add -insecure flag

### PR DESCRIPTION
**Pull request by josharian**
This makes it easier to run microproxy locally during development.

---
This change is [Reviewable](https://reviewable.io/reviews/tailscale/tailscale/765)

### CODE REVIEW

**Comment by bradfitz** [comment]
Remind me why some random production workaround(?) temporary(?) binary is in the open source tailscale/tailscale repo? Do we imagine anybody else ever needing this?

**Comment by bradfitz** [comment]
But LGTM code-wise

**Comment by josharian** [comment]
> Remind me why some random production workaround(?) temporary(?) binary is in the open source tailscale/tailscale repo? Do we imagine anybody else ever needing this?

I wondered the same thing. Unless you say otherwise, @danderson, I'll move to corp later this week.

**Comment by danderson** [comment]
It used to be a more generic "read go's expvar format and reexport as prometheus varz", and had nothing confidential in it, so I defaulted to the OSS repo. No objection to moving it to corp.

**Comment by bradfitz** [comment]
Maybe when it's moved it can be renamed too? A name about its prior size isn't as great as a name about what it actually does. (Since the second commit in 48d7ee1c6a99fd4e240ad487a6cec0333e1b47fd it's been a very specific beast worthy of a proper name)

**Pull request merged**
