### PR TITLE
ipn: remove portpoller.

### PR DESCRIPTION
**Pull request by danderson**
It's far too spammy to be of any use. We can reintroduce it once it's
at-all useful.

Signed-off-by: David Anderson <dave@natulte.net>

---
This change is [Reviewable](https://reviewable.io/reviews/tailscale/tailscale/238)

### CODE REVIEW

**Comment by bradfitz** [comment]
Please revert this. I've said twice on Slack that I want to keep this.

If you want to disable it, disable it, but don't delete all the code. It's much easier to reenable later if it's behind a bool or flag and not deleted.

**Comment by apenwarr** [comment]
The PR was closed rather than merged. See
https://github.com/tailscale/tailscale/pull/239

**Comment by bradfitz** [comment]
Ugh. I'm still not used to GitHub's emails.

**Comment by apenwarr** [comment]
I had to double check too when I saw it go by :)

**Pull request closed without merging**
