### PR TITLE
Use '-trimpath' for smaller and reproducible builds

### PR DESCRIPTION
**Pull request by bdd**
There's a quite a bit of repeated strings in the data section of binaries
which doesn't seem to get compressed in any way either.

% strings -d -1 tailscale{,d} | grep /home/dave | wc -l
1412

Adds '-trimpath' flag to GH Workflows builds.

I noticed on Twitter @bradfitz was on a productive binary size reduction rabbit hole. Point checked for this one in the released binaries.  Judging from `/home/dave` these binaries get built somewhere else, not by workflows but you maybe you can consider adding this there too.

---
This change is [Reviewable](https://reviewable.io/reviews/tailscale/tailscale/346)

### CODE REVIEW

**Comment by bradfitz** [comment]
We do this already on iOS. What's the motivation for doing it in CI?

**Comment by danderson** [comment]
We don't use these builds as release binaries, the actual build logic is in our non-OSS repository. We already use -trimpath for iOS builds, and I had a TODO to make it happen on other platforms too.

I don't think there's any need to do this in the OSS CI, since we don't use those binaries for anything. I'll port this into our corp build system and close the PR, if that works for you?

**Comment by bdd** [comment]
> We do this already on iOS. What's the motivation for doing it in CI?

As I mentioned in the last paragraph—unless I missed it—I don't think your own build scripts that generates binaries listed in https://pkgs.tailscale.com/stable/ is in this repo. So this was the only pertinent thing I managed to find and propose this change.  I don't think there's any material advantage to adding this for CI builds, so this can be just closed without merging but I think non-mobile platform builds can still use this.

**Comment by danderson** [comment]
Just added -trimpath to out corp repo's build logic. The next packages we build will have trimmed paths. Thanks for kicking this off!

**Pull request closed without merging**
