### PR TITLE
net/dnscache: use parent context to perform lookup

### PR DESCRIPTION
**Pull request by kylecarbs**
Seemingly no reason why it wasn't used.

### CODE REVIEW

**Comment by andrew-d** [comment]
@kylecarbs mind adding a `Signed-off-by` line to this commit? `git commit --amend --signoff` should do it 😄

**Comment by kylecarbs** [comment]
I have forgotten to do that so many times it's embarrassing! Yes, will do.

**Comment by andrew-d** [comment]
I took a look through this code, and I think the reason is that if the first call is canceled, other callers (that are still waiting) also see a spurious context cancelation since the first call canceled. I've submitted #12003 with a tweak to our `singleflight` package that supports proper context cancelation, which could be used here.

I'll keep you posted.

**Comment by kylecarbs** [comment]
Closing in favor of the attached PR.

**Pull request closed without merging**
