### PR TITLE
wgengine/netstack: handle multiple magicDNS queries per UDP socket

### PR DESCRIPTION
**Pull request by twitchyliquid64**
Fixes: #4686 
See: https://github.com/tailscale/tailscale/issues/4686#issuecomment-1132219403

### CODE REVIEW

**Review by bradfitz — COMMENTED** [review]
It seems like using netstack for this was a huge regression, no?

Before we just plucked these packets out as they went by and didn't have to worry about deadlines.

150ms is both too long and too short.

**Comment by twitchyliquid64** [comment]
We could in theory switch back to the old path for UDP without too much hassle: just have `handleLocalPackets` return `filter.Accept` for magicDNS UDP and it will use the old path.

I'm not happy about the extra overhead thanks to the deadline (looking through the gonet adapter, it boils down to a timer and a channel), but I don't think its the end of the world given how cold this path is.

> 150ms is both too long and too short.

Come again? :joy:

**Comment by bradfitz** [comment]
> > 150ms is both too long and too short.
>
> Come again? 😂

It's too short for the first DNS query over UDP and too long for the last one that never arrives.

**Comment by bradfitz** [comment]
What does gonet/netstack actually get us, though?

**Comment by twitchyliquid64** [comment]
> It's too short for the first DNS query over UDP and too long for the last one that never arrives.

Its fine for the first one, as the 'connection' (i.e. the `PacketConn`) doesnt actually exist till the first UDP packet comes in and gets queued to be read. Agree on it being too long though.

> What does gonet/netstack actually get us, though?

Mostly, a consistent abstraction layer (yay sockets) in an otherwise chaotic world. The bit where packets get flung around like 6 different paths within tailscaled and get mangled all over the place took me ages to get my head around.

With UDP being entirely stateless, theres no technical need for us to use netstack. I'm fine with going back to using `NextPacket()` / `EnqueuePacket()` for DNS UDP and skipping netstack, but the tradeoff there is now we have more places/paths for people to understand, rather than converging on a shared abstraction (netstack) for all our simulated traffic.

**Comment by DentonGentry** [comment]
Even for UDP I'd think there is an advantage to netstack. I don't see any IP fragmentation handling in `NextPacket()` / `EnqueuePacket()`, which very large responses might conceivably use. People with the power to do so will tailor their domain's DNS responses to fit within one packet, but then we might fragment it anyway for the 1280 byte MTU.

**Comment by bradfitz** [comment]
Oh, I hadn't even considered IP fragmentation at all.

How's that work with netstack? This PR's just doing a `c.Read` and not a `PacketConn.ReadFrom` or whatever. How do you know boundaries between multiple DNS packets and how they're different than boundaries between fragments?

**Comment by twitchyliquid64** [comment]
Defrag should happen up the stack, so we should only see each assembled packet.

I've always observed that each call to `read()` on a UDP socket returns no more than one packet (ie: not stream oriented like TCP). Now that I actually look at the manpage, it seems that semantic is only guaranteed with `recv()` / `recvfrom()`, so I'll switch to `ReadFrom`.

**Review by bradfitz — APPROVED** [review]

**Pull request merged**
