### PR TITLE
ipn/ipnlocal: deflake (mostly) TestStateMachine

### PR DESCRIPTION
**Pull request by bradfitz**
I'm sick of this flaking. Even if this isn't the right fix, it
stops the alert fatigue.

Updates #3020

### CODE REVIEW

**Comment by bradfitz** [comment]
This almost always passes now:

```
go test -v -failfast -run=StateMachine -count=100 ./ipn/ipnlocal/
```

Before it could rarely pass with 20.

**Review by josharian — APPROVED** [review]
I'd prefer t.Cleanup over defer, but OK as-is.

**Review by crawshaw — APPROVED** [review]

**Comment by bradfitz** [comment]
I prefer defer when you don't need cleanup-at-a-distance, which is what I think of t.Cleanup as for... for test helpers that need to register some cleanup. Otherwise I think defer is nicely explicit.

Is there any advantage of t.Cleanup I don't know of?

**Comment by josharian** [comment]
> Is there any advantage of t.Cleanup I don't know of?

Mainly:

* I don't have to think about where it's being called from, which makes refactoring and reviewing easier. I've noticed that as I work on tests I frequently end up converting them, usually as part of refactoring out common setup/teardown.
* It makes the intent clearer: It is intended to be test-level, not function-level, even though in this case those coincide.

But as I said, I don't feel strongly.

**Comment by bradfitz** [comment]
Sure, done. Little uglier with the closure, but it's all ugly, so no real change :)

**Pull request merged**
