### PR TITLE
tailcfg: add Hostinfo.OSVersion, DeviceModel

### PR DESCRIPTION
**Pull request by bradfitz**
This change is [Reviewable](https://reviewable.io/reviews/tailscale/tailscale/572)

### CODE REVIEW

**Comment by bradfitz** [comment]
@eliasnaur, can you populate these new fields in the Android app?

**Comment by eliasnaur** [comment]
@bradfitz sure, but where? The Android specific Hostname is set through ipn.Prefs; do you want OSVersion, DeviceModel fields on ipn.Prefs as well?

**Comment by bradfitz** [comment]
Yeah, I guess that's probably the only reasonable spot for them.

Or it could also just be a global variable in the controlclient package, really (where they're needed to be sent on the wire). Maybe with a package setter func that'd grab a mutex while setting them.

Whatever's easiest.

**Comment by eliasnaur** [comment]
https://github.com/tailscale/tailscale/pull/599

**Pull request merged**
