### PR TITLE
go.mod: bump netstack for clone reset fix

### PR DESCRIPTION
**Pull request by raggi**
In tracking down issue #4144 and reading through the netstack code in
detail, I discovered that the packet buf Clone path did not reset the
packetbuf it was getting from the sync.Pool. The fix was sent upstream
https://github.com/google/gvisor/pull/7385, and this bump pulls that in.
At this time there is no known path that this fixes, however at the time
of upstream submission this reset at least one field that could lead to
incorrect packet routing if exercised, a situation that could therefore
lead to an information leak.

### CODE REVIEW

**Review by crawshaw — APPROVED** [review]

**Comment by bradfitz** [comment]
Please reference a bug or so more.

**Comment by bradfitz** [comment]
Also "go.mod: bump netstack ..."

**Comment by raggi** [comment]
description added, sorry for not doing so first time :)

**Comment by bradfitz** [comment]
Put a # before 4144 so they're crosslinked

**Comment by raggi** [comment]
fwiw the two issues are only linked by the fact that I found the nestack bug while scouring the code for #4144 - this does not relate to it directly.

**Comment by bradfitz** [comment]
LGTM

**Pull request merged**
