### PR TITLE
add -y flag for xbps to allow installation on void

### PR DESCRIPTION
**Pull request by JayWStapleton**
install.sh failed on prompt in void. Tested with -y and installation finished.

### CODE REVIEW

**Review by JayWStapleton — COMMENTED** [review]
Signed-off-by: Jay Stapleton <jay@tailscale.com>

**Review by danderson — APPROVED** [review]
Missing DCO, you can add it with `git commit --amend -s` and then repush your branch

**Comment by bradfitz** [comment]
@JayWStapleton, the `Signed-off-by: Jay Stapleton ...` part needs to go in the git commit message itself, not in a GitHub comment.

**Comment by JayWStapleton** [comment]
> @JayWStapleton, the `Signed-off-by: Jay Stapleton ...` part needs to go in the git commit message itself, not in a GitHub comment.

I used the web front end, I need to redo it from the command line to sign off.

**Review by Xe — APPROVED** [review]

**Pull request merged**
