### PR TITLE
derp: switch from expvar to prometheus metrics.

### PR DESCRIPTION
**Pull request by danderson**
This is what it takes to monitor derp with prometheus/grafana. Efficiency is about same or better, prometheus does integer-ey things with atomic ops.

Could also use the OpenTelemetry libraries which do much the same, but also offer distributed tracing if we ever wanted it. They're still alpha though so I skipped.

### CODE REVIEW

**Comment by crawshaw** [comment]
This PR is working the linker's DCE optimization pretty heavily to keep a mountain of code out of  tailscaled. Does it work? What's the effect on binary size?

Philosophically, I'm pretty sad about this. At its core, this huge Prometheus package must have a handful of atomics per number at most, but now every leaf package needs dependencies on things like the proto library? If all those dependencies came in package main to actually send the numbers over the wire that wouldn't really bother me too much, but dragging them around everywhere feels like programming in google3. Is there no lightweight metrics library out there?

Alternatively, could we use this thingy so we only need to import the client_golang in derper's main? https://github.com/prometheus/client_golang/blob/master/prometheus/expvar_collector.go

**Comment by danderson** [comment]
Philosophically, I'd like the shortest path to some monitoring, and this is that :). I agree that the client is larger than it should have to be, but I'd also point out that binary size isn't relevant to the servers we want to instrument. I'm still not happy adding large closures, obviously, but on balance I'd still rather have monitoring.

re: expvar collector, the docs note: `Note that the data models of expvar and Prometheus are fundamentally different, and that the expvar Collector is inherently slower than native Prometheus metrics. Thus, the expvar Collector is probably great for experiments and prototying, but you should seriously consider a more direct implementation of Prometheus metrics for monitoring production systems.`

I don't much care about the performance aspect, but the data model mismatch is going to cause us pain when things like counter don't quite behave right.

I don't know of any lighter weight metric libraries that are compatible with the modern monitoring ecosystem. One possibility might be opentelemetry, which aggressively splits stuff into sub-packages, but I don't know if that actually reduces the cross-dependencies between them.

**Comment by danderson** [comment]
This branch adds 1.6MiB to cmd/derper, so your fears about code bloat are definitely justified though.

**Comment by bradfitz** [comment]
The expvar HTTP handler is a few lines:

https://github.com/golang/go/blob/c4ca60313ef7fd0b9d2c223889caeb20147309ac/src/expvar/expvar.go#L332

Can't we just write our own HTTP handler in the format that Prometheus wants?

(Format: https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exposition_formats.md)

My concern is that I'd like to add a bunch of varz to tailscaled too and that ends up in the NetworkExtension and I'd prefer if we could use the same counter types everywhere. expvar seems light.

**Comment by danderson** [comment]
`Note that the data models of expvar and Prometheus are fundamentally different`

If you want to lick that cookie and debug the monitoring when it fails, I'm okay sticking with expvar.

Of note is that we lose all the more advanced metric types, e.g. histograms. We'll also need some wrapper around expvar to define whether variables are counters or gauges (which influences the semantics of how decrements and resets are handled, to correctly preserve rate data).

**Comment by bradfitz** [comment]
> We'll also need some wrapper around expvar to define whether variables are counters or gauges

We can have naming conventions, then our HTTP handler understands those conventions and maps it to the right prometheus type.

**Comment by bradfitz** [comment]
Merged.

**Comment by danderson** [comment]
Implying variable names that contain their type information, even though the prometheus format separates the two :(.

Lemme give the opentelemetry library a try before we go this route. They seem to have designed stuff to avoid bloat and make the specific implementation selectable in main(). I'd feel more comfortable with a grown-up telemetry library as a base.

**Comment by danderson** [comment]
Never mind, the API is awful. Somehow more verbose than prometheus's.

Okay, let's do expvar munging then :((

**Comment by crawshaw** [comment]
FYI: my biggest concern above was the new dependency that's in the derp package, which is imported in tailscaled and iOS. So we are relying on the linker pulling it all out for it to not change the iOS binary size.

More generally, it would be great to have a lightweight metrics package everywhere. I'm amazed it doesn't exist already.

**Comment by danderson** [comment]
Definitely wish something lightweight existed that supports modern
telemetry. Unfortunately the metrics space seems to favor architecture
astronautics, so we're stuck with an impedance mismatch :-(

**Comment by bradfitz** [comment]
I sent https://github.com/tailscale/tailscale/pull/129 as an alternative.

**Pull request closed without merging**
