### PR TITLE
.github/workflows: add --race tests on Linux and Windows

### PR DESCRIPTION
**Pull request by alexbrainman**
Updates #50
Updates #833

### CODE REVIEW

**Comment by alexbrainman** [comment]
I run --race tests after normal tests. This adds 38s for Linux build and 1m36s for Windows build. Windows build total time is 4m26s now.

Perhaps, if we run Windows -race test in a separate build, it will be faster. Let me know, if you want me to try that.

Thank you.

Alex

**Comment by bradfitz** [comment]
Yeah, let's make them be separate jobs so they work in parallel. I don't think I even want 38 extra seconds for Linux.

**Comment by alexbrainman** [comment]
Hold on a minute.

**Comment by alexbrainman** [comment]
PTAL.

Thank you.

Alex

**Comment by alexbrainman** [comment]
Very strange. Windows non-race test is stuck. I cancel it after nearly 8 minutes.

I did not even changed that file.

I am not sure what to do here.

Alex

**Comment by alexbrainman** [comment]
PTAL

I changed commit date and pushed again to run builder again. And this time build finished successfully. No idea what happened before.

The longest build time is windows race with around 3 minutes.

Alex

**Pull request merged**
