### PR TITLE
tailcfg: add MapRequest.EndpointType

### PR DESCRIPTION
**Pull request by bradfitz**

### CODE REVIEW

**Review by danderson — APPROVED** [review]
Don't we want to trend towards less endpoint information in control, rather than more?

Seems fine if there's a necessary purpose tho.

**Comment by bradfitz** [comment]
See https://github.com/tailscale/corp/issues/1543 for background, which I apparently filed in the wrong repo.

> Now that peers exchange endpoints over DERP, we could stop sending so many endpoints from control to nodes, but some we'd still like to always advertise, notably the portmap ones (that are high quality and work right away, not requiring even a firewall traversal packet out first). By sending the portmap ones, we save an RTT for clients connecting to each other.
>
> But control doesn't know which endpoints are good or not.
> 
> So I propose we start uploading reasons.
> 
> Then control can choose which to strip later based on the peers and their versions.

**Comment by maisem** [comment]
Should we create a new Endpoint struct and add type and addr as fields? I am not a huge fan of correlating data across two different slices based on indices.

**Review by crawshaw — APPROVED** [review]
I'm fine with two parallel slices on the wire as long as we pass around a nicer struct inside our code.

I'm also fine with sending the reasons to control until we get to a point where we stop depending on control endpoint info for debugging / admin panel.

**Comment by bradfitz** [comment]
> Should we create a new Endpoint struct and add type and addr as fields? I am not a huge fan of correlating data across two different slices based on indices.

The concern is that it then requires all servers be updated before any clients. Whereas this way is just extra information which older servers can ignore.

**Comment by maisem** [comment]
> The concern is that it then requires all servers be updated before any clients. Whereas this way is just extra information which older servers can ignore.

Yeah it's going to be a pain to make anything else a backwards compatible change. LGTM

**Review by danderson — APPROVED** [review]
Having any endpoints other than DERP pushed eagerly keeps the privacy aspect of p2p endpoint exchange unfixed (I can passively monitor your endpoint changes as location hints). Still, this plan puts us on a path of having less information in control, so, +1 for now.

**Pull request merged**
