### PR TITLE
types/logger: add key grinder stats lines to rate-limiting exemption list

### PR DESCRIPTION
**Pull request by josharian**

### CODE REVIEW

**Comment by bradfitz** [comment]
I have an in-progress change with a new test, but I can just mail the test later.

**Comment by josharian** [comment]
Also happy to look at your fix if you'd prefer. I'm easy. :)

**Comment by bradfitz** [comment]
TV time. Feel free to steal my incomplete test pushed to `bradfitz/log_rate_test` just now.

**Review by bradfitz — APPROVED** [review]
Fine without tests too. I can push a test later.

**Comment by josharian** [comment]
Test stolen and completed/fixed.

**Comment by josharian** [comment]
I'll leave for you to give it a second glance tomorrow. Feel free to submit if we need it in sooner than that.

**Comment by bradfitz** [comment]
LGTM, merging

**Pull request merged**
