### PR TITLE
fuzzing: Add CIFuzz

### PR DESCRIPTION
**Pull request by AdamKorcz**
Adds CIFuzz. This will run Tailscales fuzzers for 600 seconds in the CI when a pull request is made. The time can be changed.

Documentation of CIFuzz can be found here: https://google.github.io/oss-fuzz/getting-started/continuous-integration/

This is a service offered by OSS-fuzz to help catch bugs before they are merged as well as check if a pull request will break the fuzzers.

### CODE REVIEW

**Comment by josharian** [comment]
Thanks. I think 300s would be a better choice; I'd rather have less coverage and not have to wait longer for CI to complete. I believe our slowest CI is about 5m now.

**Comment by bradfitz** [comment]
Ping @AdamKorcz.

**Comment by AdamKorcz** [comment]
Sorry, I missed this. Will update this week.

**Comment by AdamKorcz** [comment]
Changed to 300s

**Review by josharian — APPROVED** [review]

**Pull request merged**
