### PR TITLE
util/syspolicy: add policy key for onboarding flow visibility

### PR DESCRIPTION
**Pull request by dblohm7**
Updates https://github.com/tailscale/corp/issues/23789

### CODE REVIEW

**Review by nickkhyl — APPROVED** [review]
We should probably update ADMX/ADML as well.

**Comment by agottardo** [comment]
macOS already offers https://tailscale.com/kb/1315/mdm-keys#suppress-the-first-launch-onboarding-flow. 

It looks like this PR added a new policy key to control the same feature, perhaps Windows should use the same one as macOS?

@dblohm7 @nickkhyl

**Comment by nickkhyl** [comment]
@agottardo: While I agree that using a consistent policy setting key across all platforms is ideal (and thanks for noting we already have one!), I think we should also be more intentional with naming. Personally, I'd prefer `OnboardingFlow` over `TailscaleOnboardingSeen` as a policy name.

**Comment by dblohm7** [comment]
Yeah, that was my precise thought when I added these. Particularly because putting `Tailscale` in the policy setting name is not consistent with our existing policies.

**Comment by dblohm7** [comment]
(one of the nice things about moving to unified code for this is that we can be more consistent with this in the future)

**Pull request merged**
