### PR TITLE
go.toolchain.rev: bump Go toolchain

### PR DESCRIPTION
**Pull request by bradfitz**
For tailscale/go#60

### CODE REVIEW

**Comment by maisem** [comment]
Also need to bump nix

**Comment by bradfitz** [comment]
> Also need to bump nix

Nope. I used the script. Only when go.mod changes.

**Comment by bradfitz** [comment]
Plus @danderson made Nix fix itself with its own PR.

**Comment by bradfitz** [comment]
(Feel free to merge)

**Review by danderson — APPROVED** [review]

**Pull request merged**
