### PR TITLE
VERSION.txt: this is v1.49.0

### PR DESCRIPTION
**Pull request by awly**

### CODE REVIEW

**Comment by DentonGentry** [comment]
The intent is to merge this next Wednesday?

**Review by DentonGentry — CHANGES_REQUESTED** [review]
Sorry, but I'm marking this Request Changes to make sure we don't submit this today.

**Comment by awly** [comment]
My intent was to merge this today, since 1.48 will be today's `main` plus some cherry-picks. So I assumed that 1.49 should be today's `main` too.

**Comment by awly** [comment]
Discussed offline, we will cut a release branch later and keep the current version on `main` as is.

**Pull request closed without merging**
