### PR TITLE
refactor: remove extra COPY steps in Dockerfile

### PR DESCRIPTION
**Pull request by pratikbalar**
Well, it will save at least one step/layer

### CODE REVIEW

**Comment by Xe** [comment]
Can you please run these two commands to get the [Developer Certificate of Origin](https://wiki.linuxfoundation.org/dco) added to your commit message?

```
git commit --amend --no-edit --signoff
git push --force-with-lease origin patch-1
```

I can merge it after you do that!

**Review by Xe — APPROVED** [review]

**Comment by bradfitz** [comment]
And maybe fix the "aggrigate" typo as well?

**Comment by pratikbalar** [comment]
now, it's good to go @bradfitz

**Comment by bradfitz** [comment]
The commit message still has a typo in it.

**Comment by pratikbalar** [comment]
@bradfitz now ?

**Comment by bradfitz** [comment]
Instead of the "refactor: " prefix, use "Dockerfile: ".

In general, use `git log` on a file to see the style of commit messages used in the past.

**Comment by pratikbalar** [comment]
What's now @bradfitz

**Pull request merged**
