### PR TITLE
types/key: add test for NodePublic.Shard

### PR DESCRIPTION
**Pull request by bradfitz**
Updates #cleanup

### CODE REVIEW

**Comment by bradfitz** [comment]
@twitchyliquid64, how did you come up with:

```go
	s := uint8(p.k[31]) + uint8(p.k[30]) + uint8(p.k[20])
	return s ^ uint8(p.k[2]+p.k[12])
```

Because just `return p.k[0]` also passes this chi-squared test. (but not, say, `return p.k[31]`)

**Comment by twitchyliquid64** [comment]
I yeeted it to mix in bits from not the start and end of the key.

I know the key isnt uniformly random, so I wanted to grab more entropy from a random dabble of other bits.

This was for when we were experimenting with sharded locks, I don't think we ended up using this. So maybe we can delete this method entirely?

**Comment by bradfitz** [comment]
We are using it now. Hence my new interest in it. :)

**Comment by twitchyliquid64** [comment]
Ah gotcha. Well to answer your question there was no grand design to which bytes I am mashing with which other bytes - just a general desire to mix stuff from across the array because entropy is not uniform.

**Review by twitchyliquid64 — APPROVED** [review]

**Pull request merged**
