### PR TITLE
tsweb: add HTTPError.Header

### PR DESCRIPTION
**Pull request by dsnet**
The Hdr field allows the server to specify specific headers to set.
Example use case: server returns 429 with the "Retry-After" header set.

Signed-off-by: Joe Tsai <joetsai@digital-static.net>

### CODE REVIEW

**Comment by bradfitz** [comment]
Hdr is pretty short for a field name.

**Comment by dsnet** [comment]
Matches `Msg` being pretty short 😐. Do we want to be consistent or not? I personally prefer `Header` as well.

**Review by bradfitz — APPROVED** [review]
Let's go with `Header` then.

**Comment by dsnet** [comment]
Done.

**Comment by bradfitz** [comment]
typo in commit message: `tsbweb`

**Pull request merged**
