### PR TITLE
net/tstun: probe TCP GRO

### PR DESCRIPTION
**Pull request by jwhited**
Disable TCP & UDP GRO if the probe fails.

torvalds/linux@e269d79c7d35aa3808b1f3c1737d63dab504ddc8 broke virtio_net TCP & UDP GRO causing GRO writes to return EINVAL. The bug was then resolved later in
torvalds/linux@89add40066f9ed9abe5f7f886fe5789ff7e0c50e. The offending commit was pulled into various LTS releases.

Updates #13041

### CODE REVIEW

**Comment by jwhited** [comment]
waiting on https://github.com/tailscale/wireguard-go/pull/33 + go.mod update

**Review by bradfitz — APPROVED** [review]
Normally I don't approve drafts, but I know the state of this one and its dependency, so LGTM.

**Review by sailorfrag — COMMENTED** [review]
looks good, will approve after wireguard pr is merged

**Comment by jwhited** [comment]
I ended up modifying the TTL to be zero as a best effort to prevent the probe packet from leaking. It gets dropped (not visible via tcpdump) in my testing, probably due to RPF/looping, this is just extra paranoia.

**Review by sailorfrag — APPROVED** [review]

**Pull request merged**
