### PR TITLE
cmd/tailscale: make web mode preserve URL scheme in Synology redirect

### PR DESCRIPTION
**Pull request by damnever**
Error message:
```js
(index):13 Mixed Content: The page at 'https://dsm.example.local/webman/3rdparty/Tailscale/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://dsm.example.local/webman/login.cgi'. This request has been blocked; the content must be served over HTTPS.
```

### CODE REVIEW

**Comment by bradfitz** [comment]
Thanks! I'll leave this to @crawshaw to review but looks right to me.

Can you reword the commit message's title to be "cmd/tailscale: make web mode preserve URL scheme in Synology redirect"

Also, remove the unrelated newline in the imports?

**Comment by damnever** [comment]
I think the unrelated newline is added by the goimports.. I will remove it.

**Comment by bradfitz** [comment]
Ping @crawshaw.

**Comment by damnever** [comment]
Any plan to fix this?

**Review by crawshaw — APPROVED** [review]
Thanks! (Not sure how I lost this PR, I should have seen this ages ago.)

**Pull request merged**
