### PR TITLE
ipn/ipnlocal: make IPv6 OS routes be a single /48 for our ULA space

### LINKED ISSUE #1450: Make IPv6 OS routes be a single /48 for our ULA space
We program a bunch of /128s in the OS, but we entirely own the Tailscale ULA space. We can save a bunch of work by programming just a /48 and letting the entire space come to us.

We should do this for 1.6, to reduce the amount of work that very busy nodes have to do.

### PR DESCRIPTION
**Pull request by bradfitz**
And if we have over 10,000 CGNAT routes, just route the entire
CGNAT range. (for the hello test server)

Fixes #1450

### CODE REVIEW

**Comment by bradfitz** [comment]
Untested so don't merge yet.

I also should add some Go tests.

**Review by danderson — APPROVED** [review]

**Comment by danderson** [comment]
Dropping an LGTM for when you're ready, because it LGTM.

**Comment by bradfitz** [comment]
Manual testing:

```
# ip -6 route show table all | grep tailscale
fd7a:115c:a1e0::/48 dev tailscale0 table 52 metric 1024 pref medium
fd7a:115c:a1e0:ab12:4843:cd96:624a:4603 dev tailscale0 proto kernel metric 256 pref medium
fe80::/64 dev tailscale0 proto kernel metric 256 pref medium
local fd7a:115c:a1e0:ab12:4843:cd96:624a:4603 dev tailscale0 table local proto kernel metric 0 pref medium
local fe80::2178:c2f0:2c8a:32e6 dev tailscale0 table local proto kernel metric 0 pref medium
ff00::/8 dev tailscale0 table local metric 256 pref medium
```

**Comment by danderson** [comment]
The routes look about right.

**Comment by bradfitz** [comment]
Can ping mon:

```
$ ping fd7a:115c:a1e0:ab12:4843:cd96:6258:b240
PING fd7a:115c:a1e0:ab12:4843:cd96:6258:b240(fd7a:115c:a1e0:ab12:4843:cd96:6258:b240) 56 data bytes
64 bytes from fd7a:115c:a1e0:ab12:4843:cd96:6258:b240: icmp_seq=1 ttl=64 time=23.8 ms
64 bytes from fd7a:115c:a1e0:ab12:4843:cd96:6258:b240: icmp_seq=2 ttl=64 time=20.5 ms
64 bytes from fd7a:115c:a1e0:ab12:4843:cd96:6258:b240: icmp_seq=3 ttl=64 time=20.5 ms
64 bytes from fd7a:115c:a1e0:ab12:4843:cd96:6258:b240: icmp_seq=4 ttl=64 time=20.3 ms
64 bytes from fd7a:115c:a1e0:ab12:4843:cd96:6258:b240: icmp_seq=5 ttl=64 time=20.5 ms
```

**Comment by bradfitz** [comment]
PTAL; now has tests.

**Pull request merged**
