### PR TITLE
cmd/tailscale/cli: don't force an interactive login on --reset.

### LINKED ISSUE #1778: tailscale up --reset forces reauth
To work around #1777, I tried `tailscale up --reset`, and got forced back into the auth flow.

Isn't --reset supposed to merely let me alter my prefs at will, rather than force a reauth? cc @bradfitz

### PR DESCRIPTION
**Pull request by danderson**
Fixes #1778

Signed-off-by: David Anderson <danderson@tailscale.com>

### CODE REVIEW

**Comment by bradfitz** [comment]
That seems too simplistic a fix. I'm afraid it breaks other combinations.

I'm working towards making the CLI all tested & easy to reason about but I didn't make it all the way this cycle. That whole notify callback state machine stuff got pushed down but I didn't remove it.

**Comment by danderson** [comment]
What other combinations get broken? AFAICT, this is the exact code we used to have before all the new flag-munging logic.

**Comment by bradfitz** [comment]
Look at 1.6.0:

https://github.com/tailscale/tailscale/blob/v1.6.0/cmd/tailscale/cli/up.go

It does:

```go
	bc.Start(opts)
	if upArgs.forceReauth {
		printed = true
		startLoginInteractive()
	}
	pump(ctx, bc, c)
```

You just unconditionally deleted it in this PR, so I presume this breaks `--force-reauth` now?

**Comment by danderson** [comment]
Working on a fix. I don't think it's acceptable to ship --reset that implicitly forces reauth, but the other engine changes have broken this logic in other ways.

**Comment by danderson** [comment]
okay, --force-reauth is now handled. I tested all combinations of {,--reset,--force-reauth}, and all do the expected thing except a naked `tailscale up` when logged out - which I'm going to fix in a separate change. But this change does make reset and force-reauth work as desired.

**Review by bradfitz — APPROVED** [review]
Thanks!

**Pull request merged**
