### PR TITLE
ipn/policy: mark AppConnector service as interesting

### PR DESCRIPTION
**Pull request by raggi**
Updates #15437
Signed-off-by: James Tucker <james@tailscale.com>

### CODE REVIEW

**Review by catzkorn — APPROVED** [review]
very interesting

**Review by twitchyliquid64 — APPROVED** [review]
ditto, much interestings

**Review by bradfitz — COMMENTED** [review]
Oh no, we're extending this hack more, eh? We keep talking about killing it :(

**Comment by raggi** [comment]
> Oh no, we're extending this hack more, eh? We keep talking about killing it :(

We are currently, but we could move it.

Do you have a preferred place to transport this that's easy to access in the map responder?

**Pull request merged**
