### PR TITLE
build_docker.sh: add run.sh as an entrypoint to the docker image

### LINKED ISSUE #4071: FR: Provide entrypoint for the Docker container
### What are you trying to do?

I'm trying to run a Tailscale subnet router on ECS Fargate.

Currently I have this entrypoint, cribbed from https://github.com/tailscale/tailscale/blob/main/docs/k8s/run.sh. It's a bit awkward running `tailscaled` and `tailscale` in the same container.

```
entrypoint = ["/bin/sh", "-c", "tailscaled --tun=userspace-networking & PID=$!; tailscale up --authkey $TAILSCALE_AUTHKEY --advertise-routes=10.30.0.0/16,10.31.0.0/16,10.32.0.0/16 --accept-dns=false && wait $PID"]
```

### How should we solve this?

I would imagine providing something similar to the [run.sh](https://github.com/tailscale/tailscale/blob/main/docs/k8s/run.sh) would work pretty well and be generally useful. It would let users provide flags for `tailscaled` and `tailscale` and reliably handle failures from both.

### What is the impact of not solving this?

If I want to get a more robust script my options are (I think):

1. Create and publish a new Docker image which adds a script to the built-in container. This is fine but adds more maintenance cost to update it.
2. Source the full script in the entrypoint (if it would fit)

### Anything else?

Here's part of my Terraform config for this:

<details>

```terraform
resource "aws_ecs_task_definition" "tailscale" {
  # ...
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"

  container_definitions = jsonencode([
    {
      name       = "tailscale"
      image      = "tailscale/tailscale:v1.22.0"
      entrypoint = ["/bin/sh", "-c", "tailscaled --tun=userspace-networking & PID=$!; tailscale up --authkey $TAILSCALE_AUTHKEY --advertise-routes=10.30.0.0/16,10.31.0.0/16,10.32.0.0/16 --accept-dns=false && wait $PID"]

      essential = true
      secrets = [{
        "name" : "TAILSCALE_AUTHKEY",
        "valueFrom" : local.ts_subnet_router_authkey
      }]
    }
  ])
}
```

</details>

### PR DESCRIPTION
**Pull request by maisem**
Fixes #4071

Signed-off-by: Maisem Ali <maisem@tailscale.com>

### CODE REVIEW

**Review by bradfitz — APPROVED** [review]

**Comment by maisem** [comment]
I tested locally, working on setting up a k8s cluster.

**Comment by maisem** [comment]
> LGTM. Normally we don't bump copyright years, btw.
> 
> Have you tested this after recent rename edits?

Yeah, confirmed that it works.

**Comment by shadycuz** [comment]
@maisem I was looking at which docker containers have this new feature https://hub.docker.com/r/tailscale/tailscale/tags and thats when I noticed that dockerhub lists tailscale `1.27.X` and this repo only goes up to `1.26.X` is that a bug? Did someone accidentally push the wrong tag to dockerhub?

**Comment by maisem** [comment]
@shadycuz odd numbers are built from HEAD and signify unstable builds

**Comment by shadycuz** [comment]
@maisem  Thanks =), I see your commit is referenced in the `1.26.0` and `1.26.1` tags, so I'm guessing I will find your changes in those docker containers <3. 

Thanks for this. It was really important and will make tailscale much easier to implement on K8's. 🎉

**Pull request merged**
