### PR TITLE
words: scaly fruit salad? go fly a kite

### PR DESCRIPTION
**Pull request by thisisparker**
Some tails, some scales.

This is my first commit in this package so please let me know if I'm doing something wrong!

### CODE REVIEW

**Comment by bradfitz** [comment]
The commits should start with "words: "

**Comment by catzkorn** [comment]
We already have salak! :D

**Comment by thisisparker** [comment]
> We already have salak! :D

so we do! I saw it referenced in an article about cherimoya and I guess I was too excited to check?!

**Comment by clairew** [comment]
squash to 1 commit that says something like "add fruit to scales add kite to tails"

**Review by catzkorn — APPROVED** [review]

**Pull request merged**
