### PR TITLE
control/controlclient, wgengine/magicsock: ignore pre-disco (pre-0.100) peers

### PR DESCRIPTION
**Pull request by bradfitz**
There aren't any in the wild, other than one we ran on purpose to keep us honest, but we can bump that one forward to 0.100.

### CODE REVIEW

**Comment by DentonGentry** [comment]
🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉

Oh this will be SOOO nice.

**Review by phirework — COMMENTED** [review]
We just need to remove `TestNoDiscoKey` from the test suite.

**Comment by bradfitz** [comment]
> We just need to remove TestNoDiscoKey from the test suite.

Done.

**Comment by bradfitz** [comment]
PTAL. Ended up going a different route, as an integration test revealed the old way was broken a bit.

**Review by phirework — APPROVED** [review]

**Pull request merged**
